// this file is auto-generated by go-gi

package gtk

// #cgo pkg-config: gtk+-3.0 gobject-2.0
// #include <string.h>
// #include <glib-object.h>
// #include <glib/gstdio.h>
// #include <glib-unix.h>
// #include <gtk/gtkx.h>
/*
gboolean _true() { return TRUE; }
gboolean _false() { return FALSE; }
GTokenType _gtk_binding_entry_add_signal_from_string(GtkBindingSet* binding_set, gchar* signal_desc) {
	return gtk_binding_entry_add_signal_from_string(binding_set, (const gchar*)(signal_desc));
}
void _gtk_binding_entry_add_signall(GtkBindingSet* binding_set, guint keyval, GdkModifierType modifiers, gchar* signal_name, GSList* binding_args) {
	gtk_binding_entry_add_signall(binding_set, keyval, modifiers, (const gchar*)(signal_name), binding_args);
}
GtkBindingSet* _gtk_binding_set_find(gchar* set_name) {
	return gtk_binding_set_find((const gchar*)(set_name));
}
GtkBindingSet* _gtk_binding_set_new(gchar* set_name) {
	return gtk_binding_set_new((const gchar*)(set_name));
}
GParamSpec* _gtk_cell_area_class_find_cell_property(GtkCellAreaClass* self, gchar* property_name) {
	return gtk_cell_area_class_find_cell_property((GtkCellAreaClass*)(self), (const gchar*)(property_name));
}
GParamSpec* _gtk_container_class_find_child_property(GtkContainerClass* self, gchar* property_name) {
	return gtk_container_class_find_child_property((GtkContainerClass*)(self), (const gchar*)(property_name));
}
gboolean _gtk_gradient_resolve(GtkGradient* self, GtkStyleProperties* props, void* resolved_gradient) {
	return gtk_gradient_resolve((GtkGradient*)(self), props, (cairo_pattern_t**)(resolved_gradient));
}
gboolean _gtk_icon_info_get_attach_points(GtkIconInfo* self, void* points, gint* n_points) {
	return gtk_icon_info_get_attach_points((GtkIconInfo*)(self), (GdkPoint**)(points), n_points);
}
GdkPixbuf* _gtk_icon_info_load_icon(GtkIconInfo* self, void* err) {
	return gtk_icon_info_load_icon((GtkIconInfo*)(self), (GError**)(err));
}
GdkPixbuf* _gtk_icon_info_load_symbolic(GtkIconInfo* self, GdkRGBA* fg, GdkRGBA* success_color, GdkRGBA* warning_color, GdkRGBA* error_color, gboolean* was_symbolic, void* err) {
	return gtk_icon_info_load_symbolic((GtkIconInfo*)(self), (const GdkRGBA*)(fg), (const GdkRGBA*)(success_color), (const GdkRGBA*)(warning_color), (const GdkRGBA*)(error_color), was_symbolic, (GError**)(err));
}
GdkPixbuf* _gtk_icon_info_load_symbolic_for_context(GtkIconInfo* self, GtkStyleContext* context, gboolean* was_symbolic, void* err) {
	return gtk_icon_info_load_symbolic_for_context((GtkIconInfo*)(self), context, was_symbolic, (GError**)(err));
}
void _gtk_icon_set_add_source(GtkIconSet* self, GtkIconSource* source) {
	gtk_icon_set_add_source((GtkIconSet*)(self), (const GtkIconSource*)(source));
}
void _gtk_icon_set_get_sizes(GtkIconSet* self, void* sizes, gint* n_sizes) {
	gtk_icon_set_get_sizes((GtkIconSet*)(self), (GtkIconSize**)(sizes), n_sizes);
}
void _gtk_icon_source_set_icon_name(GtkIconSource* self, gchar* icon_name) {
	gtk_icon_source_set_icon_name((GtkIconSource*)(self), (const gchar*)(icon_name));
}
GtkPaperSize* _gtk_paper_size_new(gchar* name) {
	return gtk_paper_size_new((const gchar*)(name));
}
GtkPaperSize* _gtk_paper_size_new_custom(gchar* name, gchar* display_name, gdouble width, gdouble height, GtkUnit unit) {
	return gtk_paper_size_new_custom((const gchar*)(name), (const gchar*)(display_name), width, height, unit);
}
GtkPaperSize* _gtk_paper_size_new_from_key_file(GKeyFile* key_file, gchar* group_name, void* err) {
	return gtk_paper_size_new_from_key_file(key_file, (const gchar*)(group_name), (GError**)(err));
}
GtkPaperSize* _gtk_paper_size_new_from_ppd(gchar* ppd_name, gchar* ppd_display_name, gdouble width, gdouble height) {
	return gtk_paper_size_new_from_ppd((const gchar*)(ppd_name), (const gchar*)(ppd_display_name), width, height);
}
void _gtk_paper_size_to_key_file(GtkPaperSize* self, GKeyFile* key_file, gchar* group_name) {
	gtk_paper_size_to_key_file((GtkPaperSize*)(self), key_file, (const gchar*)(group_name));
}
GAppInfo* _gtk_recent_info_create_app_info(GtkRecentInfo* self, gchar* app_name, void* err) {
	return gtk_recent_info_create_app_info((GtkRecentInfo*)(self), (const gchar*)(app_name), (GError**)(err));
}
gboolean _gtk_recent_info_get_application_info(GtkRecentInfo* self, gchar* app_name, void* app_exec, guint* count, time_t* time_) {
	return gtk_recent_info_get_application_info((GtkRecentInfo*)(self), (const gchar*)(app_name), (const gchar**)(app_exec), count, time_);
}
gboolean _gtk_recent_info_has_application(GtkRecentInfo* self, gchar* app_name) {
	return gtk_recent_info_has_application((GtkRecentInfo*)(self), (const gchar*)(app_name));
}
gboolean _gtk_recent_info_has_group(GtkRecentInfo* self, gchar* group_name) {
	return gtk_recent_info_has_group((GtkRecentInfo*)(self), (const gchar*)(group_name));
}
gboolean _gtk_selection_data_get_targets(GtkSelectionData* self, void* targets, gint* n_atoms) {
	return gtk_selection_data_get_targets((GtkSelectionData*)(self), (GdkAtom**)(targets), n_atoms);
}
gboolean _gtk_selection_data_set_text(GtkSelectionData* self, gchar* str, gint len_) {
	return gtk_selection_data_set_text((GtkSelectionData*)(self), (const gchar*)(str), len_);
}
gboolean _gtk_selection_data_set_uris(GtkSelectionData* self, void* uris) {
	return gtk_selection_data_set_uris((GtkSelectionData*)(self), (gchar**)(uris));
}
GtkSymbolicColor* _gtk_symbolic_color_new_literal(GdkRGBA* color) {
	return gtk_symbolic_color_new_literal((const GdkRGBA*)(color));
}
GtkSymbolicColor* _gtk_symbolic_color_new_name(gchar* name) {
	return gtk_symbolic_color_new_name((const gchar*)(name));
}
GtkSymbolicColor* _gtk_symbolic_color_new_win32(gchar* theme_class, gint id) {
	return gtk_symbolic_color_new_win32((const gchar*)(theme_class), id);
}
GtkTargetEntry* _gtk_target_entry_new(gchar* target, guint flags, guint info) {
	return gtk_target_entry_new((const gchar*)(target), flags, info);
}
void _gtk_text_iter_assign(GtkTextIter* self, GtkTextIter* other) {
	gtk_text_iter_assign((GtkTextIter*)(self), (const GtkTextIter*)(other));
}
gboolean _gtk_text_iter_backward_find_char(GtkTextIter* self, GtkTextCharPredicate pred, gpointer user_data, GtkTextIter* limit) {
	return gtk_text_iter_backward_find_char((GtkTextIter*)(self), pred, user_data, (const GtkTextIter*)(limit));
}
gboolean _gtk_text_iter_backward_search(GtkTextIter* self, gchar* str, GtkTextSearchFlags flags, GtkTextIter* match_start, GtkTextIter* match_end, GtkTextIter* limit) {
	return gtk_text_iter_backward_search((GtkTextIter*)(self), (const gchar*)(str), flags, match_start, match_end, (const GtkTextIter*)(limit));
}
gint _gtk_text_iter_compare(GtkTextIter* self, GtkTextIter* rhs) {
	return gtk_text_iter_compare((GtkTextIter*)(self), (const GtkTextIter*)(rhs));
}
gboolean _gtk_text_iter_equal(GtkTextIter* self, GtkTextIter* rhs) {
	return gtk_text_iter_equal((GtkTextIter*)(self), (const GtkTextIter*)(rhs));
}
gboolean _gtk_text_iter_forward_find_char(GtkTextIter* self, GtkTextCharPredicate pred, gpointer user_data, GtkTextIter* limit) {
	return gtk_text_iter_forward_find_char((GtkTextIter*)(self), pred, user_data, (const GtkTextIter*)(limit));
}
gboolean _gtk_text_iter_forward_search(GtkTextIter* self, gchar* str, GtkTextSearchFlags flags, GtkTextIter* match_start, GtkTextIter* match_end, GtkTextIter* limit) {
	return gtk_text_iter_forward_search((GtkTextIter*)(self), (const gchar*)(str), flags, match_start, match_end, (const GtkTextIter*)(limit));
}
gchar* _gtk_text_iter_get_slice(GtkTextIter* self, GtkTextIter* end) {
	return gtk_text_iter_get_slice((GtkTextIter*)(self), (const GtkTextIter*)(end));
}
gchar* _gtk_text_iter_get_text(GtkTextIter* self, GtkTextIter* end) {
	return gtk_text_iter_get_text((GtkTextIter*)(self), (const GtkTextIter*)(end));
}
gchar* _gtk_text_iter_get_visible_slice(GtkTextIter* self, GtkTextIter* end) {
	return gtk_text_iter_get_visible_slice((GtkTextIter*)(self), (const GtkTextIter*)(end));
}
gchar* _gtk_text_iter_get_visible_text(GtkTextIter* self, GtkTextIter* end) {
	return gtk_text_iter_get_visible_text((GtkTextIter*)(self), (const GtkTextIter*)(end));
}
gboolean _gtk_text_iter_in_range(GtkTextIter* self, GtkTextIter* start, GtkTextIter* end) {
	return gtk_text_iter_in_range((GtkTextIter*)(self), (const GtkTextIter*)(start), (const GtkTextIter*)(end));
}
GtkTreePath* _gtk_tree_path_new_from_string(gchar* path) {
	return gtk_tree_path_new_from_string((const gchar*)(path));
}
gint _gtk_tree_path_compare(GtkTreePath* self, GtkTreePath* b) {
	return gtk_tree_path_compare((GtkTreePath*)(self), (const GtkTreePath*)(b));
}
GParamSpec* _gtk_widget_class_find_style_property(GtkWidgetClass* self, gchar* property_name) {
	return gtk_widget_class_find_style_property((GtkWidgetClass*)(self), (const gchar*)(property_name));
}
void _gtk_widget_path_iter_add_class(GtkWidgetPath* self, gint pos, gchar* name) {
	gtk_widget_path_iter_add_class((GtkWidgetPath*)(self), pos, (const gchar*)(name));
}
void _gtk_widget_path_iter_add_region(GtkWidgetPath* self, gint pos, gchar* name, GtkRegionFlags flags) {
	gtk_widget_path_iter_add_region((GtkWidgetPath*)(self), pos, (const gchar*)(name), flags);
}
gboolean _gtk_widget_path_iter_has_class(GtkWidgetPath* self, gint pos, gchar* name) {
	return gtk_widget_path_iter_has_class((GtkWidgetPath*)(self), pos, (const gchar*)(name));
}
gboolean _gtk_widget_path_iter_has_name(GtkWidgetPath* self, gint pos, gchar* name) {
	return gtk_widget_path_iter_has_name((GtkWidgetPath*)(self), pos, (const gchar*)(name));
}
gboolean _gtk_widget_path_iter_has_region(GtkWidgetPath* self, gint pos, gchar* name, GtkRegionFlags* flags) {
	return gtk_widget_path_iter_has_region((GtkWidgetPath*)(self), pos, (const gchar*)(name), flags);
}
void _gtk_widget_path_iter_remove_class(GtkWidgetPath* self, gint pos, gchar* name) {
	gtk_widget_path_iter_remove_class((GtkWidgetPath*)(self), pos, (const gchar*)(name));
}
void _gtk_widget_path_iter_remove_region(GtkWidgetPath* self, gint pos, gchar* name) {
	gtk_widget_path_iter_remove_region((GtkWidgetPath*)(self), pos, (const gchar*)(name));
}
void _gtk_widget_path_iter_set_name(GtkWidgetPath* self, gint pos, gchar* name) {
	gtk_widget_path_iter_set_name((GtkWidgetPath*)(self), pos, (const gchar*)(name));
}
void _gtk_accelerator_parse(gchar* accelerator, guint* accelerator_key, GdkModifierType* accelerator_mods) {
	gtk_accelerator_parse((const gchar*)(accelerator), accelerator_key, accelerator_mods);
}
void _gtk_accelerator_parse_with_keycode(gchar* accelerator, guint* accelerator_key, void* accelerator_codes, GdkModifierType* accelerator_mods) {
	gtk_accelerator_parse_with_keycode((const gchar*)(accelerator), accelerator_key, (guint**)(accelerator_codes), accelerator_mods);
}
void _gtk_drag_set_icon_name(GdkDragContext* context, gchar* icon_name, gint hot_x, gint hot_y) {
	gtk_drag_set_icon_name(context, (const gchar*)(icon_name), hot_x, hot_y);
}
void _gtk_drag_set_icon_stock(GdkDragContext* context, gchar* stock_id, gint hot_x, gint hot_y) {
	gtk_drag_set_icon_stock(context, (const gchar*)(stock_id), hot_x, hot_y);
}
GtkIconSize _gtk_icon_size_from_name(gchar* name) {
	return gtk_icon_size_from_name((const gchar*)(name));
}
GtkIconSize _gtk_icon_size_register(gchar* name, gint width, gint height) {
	return gtk_icon_size_register((const gchar*)(name), width, height);
}
void _gtk_icon_size_register_alias(gchar* alias, GtkIconSize target) {
	gtk_icon_size_register_alias((const gchar*)(alias), target);
}
void _gtk_init(int* argc, void* argv) {
	gtk_init(argc, (char***)(argv));
}
gboolean _gtk_init_check(int* argc, void* argv) {
	return gtk_init_check(argc, (char***)(argv));
}
gboolean _gtk_init_with_args(gint* argc, void* argv, gchar* parameter_string, GOptionEntry* entries, gchar* translation_domain, void* err) {
	return gtk_init_with_args(argc, (gchar***)(argv), (const gchar*)(parameter_string), entries, (const gchar*)(translation_domain), (GError**)(err));
}
gboolean _gtk_parse_args(int* argc, void* argv) {
	return gtk_parse_args(argc, (char***)(argv));
}
gboolean _gtk_rc_property_parse_border(GParamSpec* pspec, GString* gstring, GValue* property_value) {
	return gtk_rc_property_parse_border((const GParamSpec*)(pspec), (const GString*)(gstring), property_value);
}
gboolean _gtk_rc_property_parse_color(GParamSpec* pspec, GString* gstring, GValue* property_value) {
	return gtk_rc_property_parse_color((const GParamSpec*)(pspec), (const GString*)(gstring), property_value);
}
gboolean _gtk_rc_property_parse_enum(GParamSpec* pspec, GString* gstring, GValue* property_value) {
	return gtk_rc_property_parse_enum((const GParamSpec*)(pspec), (const GString*)(gstring), property_value);
}
gboolean _gtk_rc_property_parse_flags(GParamSpec* pspec, GString* gstring, GValue* property_value) {
	return gtk_rc_property_parse_flags((const GParamSpec*)(pspec), (const GString*)(gstring), property_value);
}
gboolean _gtk_rc_property_parse_requisition(GParamSpec* pspec, GString* gstring, GValue* property_value) {
	return gtk_rc_property_parse_requisition((const GParamSpec*)(pspec), (const GString*)(gstring), property_value);
}
GdkPixbuf* _gtk_render_icon_pixbuf(GtkStyleContext* context, GtkIconSource* source, GtkIconSize size) {
	return gtk_render_icon_pixbuf(context, (const GtkIconSource*)(source), size);
}
gboolean _gtk_show_uri(GdkScreen* screen, gchar* uri, guint32 timestamp, void* err) {
	return gtk_show_uri(screen, (const gchar*)(uri), timestamp, (GError**)(err));
}
gboolean _gtk_stock_lookup(gchar* stock_id, GtkStockItem* item) {
	return gtk_stock_lookup((const gchar*)(stock_id), item);
}
void _gtk_stock_set_translate_func(gchar* domain, GtkTranslateFunc func_, gpointer data, GDestroyNotify notify) {
	gtk_stock_set_translate_func((const gchar*)(domain), func_, data, notify);
}
GtkWidget* _gtk_test_create_simple_window(gchar* window_title, gchar* dialog_text) {
	return gtk_test_create_simple_window((const gchar*)(window_title), (const gchar*)(dialog_text));
}
GtkWidget* _gtk_test_find_label(GtkWidget* widget, gchar* label_pattern) {
	return gtk_test_find_label(widget, (const gchar*)(label_pattern));
}
GtkWidget* _gtk_test_find_widget(GtkWidget* widget, gchar* label_pattern, GType widget_type) {
	return gtk_test_find_widget(widget, (const gchar*)(label_pattern), widget_type);
}
void _gtk_test_text_set(GtkWidget* widget, gchar* string_) {
	gtk_test_text_set(widget, (const gchar*)(string_));
}
gboolean _gtk_tree_get_row_drag_data(GtkSelectionData* selection_data, void* tree_model, void* path) {
	return gtk_tree_get_row_drag_data(selection_data, (GtkTreeModel**)(tree_model), (GtkTreePath**)(path));
}
*/
import "C"
import (
	"unsafe"
	"runtime"
)

const ALIGN_FILL = C.GTK_ALIGN_FILL
const ALIGN_START = C.GTK_ALIGN_START
const ALIGN_END = C.GTK_ALIGN_END
const ALIGN_CENTER = C.GTK_ALIGN_CENTER
const ARROWS_BOTH = C.GTK_ARROWS_BOTH
const ARROWS_START = C.GTK_ARROWS_START
const ARROWS_END = C.GTK_ARROWS_END
const ARROW_UP = C.GTK_ARROW_UP
const ARROW_DOWN = C.GTK_ARROW_DOWN
const ARROW_LEFT = C.GTK_ARROW_LEFT
const ARROW_RIGHT = C.GTK_ARROW_RIGHT
const ARROW_NONE = C.GTK_ARROW_NONE
const ASSISTANT_PAGE_CONTENT = C.GTK_ASSISTANT_PAGE_CONTENT
const ASSISTANT_PAGE_INTRO = C.GTK_ASSISTANT_PAGE_INTRO
const ASSISTANT_PAGE_CONFIRM = C.GTK_ASSISTANT_PAGE_CONFIRM
const ASSISTANT_PAGE_SUMMARY = C.GTK_ASSISTANT_PAGE_SUMMARY
const ASSISTANT_PAGE_PROGRESS = C.GTK_ASSISTANT_PAGE_PROGRESS
const ASSISTANT_PAGE_CUSTOM = C.GTK_ASSISTANT_PAGE_CUSTOM
const BORDER_STYLE_NONE = C.GTK_BORDER_STYLE_NONE
const BORDER_STYLE_SOLID = C.GTK_BORDER_STYLE_SOLID
const BORDER_STYLE_INSET = C.GTK_BORDER_STYLE_INSET
const BORDER_STYLE_OUTSET = C.GTK_BORDER_STYLE_OUTSET
const BORDER_STYLE_HIDDEN = C.GTK_BORDER_STYLE_HIDDEN
const BORDER_STYLE_DOTTED = C.GTK_BORDER_STYLE_DOTTED
const BORDER_STYLE_DASHED = C.GTK_BORDER_STYLE_DASHED
const BORDER_STYLE_DOUBLE = C.GTK_BORDER_STYLE_DOUBLE
const BORDER_STYLE_GROOVE = C.GTK_BORDER_STYLE_GROOVE
const BORDER_STYLE_RIDGE = C.GTK_BORDER_STYLE_RIDGE
const BUILDER_ERROR_INVALID_TYPE_FUNCTION = C.GTK_BUILDER_ERROR_INVALID_TYPE_FUNCTION
const BUILDER_ERROR_UNHANDLED_TAG = C.GTK_BUILDER_ERROR_UNHANDLED_TAG
const BUILDER_ERROR_MISSING_ATTRIBUTE = C.GTK_BUILDER_ERROR_MISSING_ATTRIBUTE
const BUILDER_ERROR_INVALID_ATTRIBUTE = C.GTK_BUILDER_ERROR_INVALID_ATTRIBUTE
const BUILDER_ERROR_INVALID_TAG = C.GTK_BUILDER_ERROR_INVALID_TAG
const BUILDER_ERROR_MISSING_PROPERTY_VALUE = C.GTK_BUILDER_ERROR_MISSING_PROPERTY_VALUE
const BUILDER_ERROR_INVALID_VALUE = C.GTK_BUILDER_ERROR_INVALID_VALUE
const BUILDER_ERROR_VERSION_MISMATCH = C.GTK_BUILDER_ERROR_VERSION_MISMATCH
const BUILDER_ERROR_DUPLICATE_ID = C.GTK_BUILDER_ERROR_DUPLICATE_ID
const BUTTONBOX_SPREAD = C.GTK_BUTTONBOX_SPREAD
const BUTTONBOX_EDGE = C.GTK_BUTTONBOX_EDGE
const BUTTONBOX_START = C.GTK_BUTTONBOX_START
const BUTTONBOX_END = C.GTK_BUTTONBOX_END
const BUTTONBOX_CENTER = C.GTK_BUTTONBOX_CENTER
const BUTTONS_NONE = C.GTK_BUTTONS_NONE
const BUTTONS_OK = C.GTK_BUTTONS_OK
const BUTTONS_CLOSE = C.GTK_BUTTONS_CLOSE
const BUTTONS_CANCEL = C.GTK_BUTTONS_CANCEL
const BUTTONS_YES_NO = C.GTK_BUTTONS_YES_NO
const BUTTONS_OK_CANCEL = C.GTK_BUTTONS_OK_CANCEL
const CELL_RENDERER_ACCEL_MODE_GTK = C.GTK_CELL_RENDERER_ACCEL_MODE_GTK
const CELL_RENDERER_ACCEL_MODE_OTHER = C.GTK_CELL_RENDERER_ACCEL_MODE_OTHER
const CELL_RENDERER_MODE_INERT = C.GTK_CELL_RENDERER_MODE_INERT
const CELL_RENDERER_MODE_ACTIVATABLE = C.GTK_CELL_RENDERER_MODE_ACTIVATABLE
const CELL_RENDERER_MODE_EDITABLE = C.GTK_CELL_RENDERER_MODE_EDITABLE
const CORNER_TOP_LEFT = C.GTK_CORNER_TOP_LEFT
const CORNER_BOTTOM_LEFT = C.GTK_CORNER_BOTTOM_LEFT
const CORNER_TOP_RIGHT = C.GTK_CORNER_TOP_RIGHT
const CORNER_BOTTOM_RIGHT = C.GTK_CORNER_BOTTOM_RIGHT
const CSS_PROVIDER_ERROR_FAILED = C.GTK_CSS_PROVIDER_ERROR_FAILED
const CSS_PROVIDER_ERROR_SYNTAX = C.GTK_CSS_PROVIDER_ERROR_SYNTAX
const CSS_PROVIDER_ERROR_IMPORT = C.GTK_CSS_PROVIDER_ERROR_IMPORT
const CSS_PROVIDER_ERROR_NAME = C.GTK_CSS_PROVIDER_ERROR_NAME
const CSS_PROVIDER_ERROR_DEPRECATED = C.GTK_CSS_PROVIDER_ERROR_DEPRECATED
const CSS_PROVIDER_ERROR_UNKNOWN_VALUE = C.GTK_CSS_PROVIDER_ERROR_UNKNOWN_VALUE
const CSS_SECTION_DOCUMENT = C.GTK_CSS_SECTION_DOCUMENT
const CSS_SECTION_IMPORT = C.GTK_CSS_SECTION_IMPORT
const CSS_SECTION_COLOR_DEFINITION = C.GTK_CSS_SECTION_COLOR_DEFINITION
const CSS_SECTION_BINDING_SET = C.GTK_CSS_SECTION_BINDING_SET
const CSS_SECTION_RULESET = C.GTK_CSS_SECTION_RULESET
const CSS_SECTION_SELECTOR = C.GTK_CSS_SECTION_SELECTOR
const CSS_SECTION_DECLARATION = C.GTK_CSS_SECTION_DECLARATION
const CSS_SECTION_VALUE = C.GTK_CSS_SECTION_VALUE
const CSS_SECTION_KEYFRAMES = C.GTK_CSS_SECTION_KEYFRAMES
const DELETE_CHARS = C.GTK_DELETE_CHARS
const DELETE_WORD_ENDS = C.GTK_DELETE_WORD_ENDS
const DELETE_WORDS = C.GTK_DELETE_WORDS
const DELETE_DISPLAY_LINES = C.GTK_DELETE_DISPLAY_LINES
const DELETE_DISPLAY_LINE_ENDS = C.GTK_DELETE_DISPLAY_LINE_ENDS
const DELETE_PARAGRAPH_ENDS = C.GTK_DELETE_PARAGRAPH_ENDS
const DELETE_PARAGRAPHS = C.GTK_DELETE_PARAGRAPHS
const DELETE_WHITESPACE = C.GTK_DELETE_WHITESPACE
const DIR_TAB_FORWARD = C.GTK_DIR_TAB_FORWARD
const DIR_TAB_BACKWARD = C.GTK_DIR_TAB_BACKWARD
const DIR_UP = C.GTK_DIR_UP
const DIR_DOWN = C.GTK_DIR_DOWN
const DIR_LEFT = C.GTK_DIR_LEFT
const DIR_RIGHT = C.GTK_DIR_RIGHT
const DRAG_RESULT_SUCCESS = C.GTK_DRAG_RESULT_SUCCESS
const DRAG_RESULT_NO_TARGET = C.GTK_DRAG_RESULT_NO_TARGET
const DRAG_RESULT_USER_CANCELLED = C.GTK_DRAG_RESULT_USER_CANCELLED
const DRAG_RESULT_TIMEOUT_EXPIRED = C.GTK_DRAG_RESULT_TIMEOUT_EXPIRED
const DRAG_RESULT_GRAB_BROKEN = C.GTK_DRAG_RESULT_GRAB_BROKEN
const DRAG_RESULT_ERROR = C.GTK_DRAG_RESULT_ERROR
const ENTRY_ICON_PRIMARY = C.GTK_ENTRY_ICON_PRIMARY
const ENTRY_ICON_SECONDARY = C.GTK_ENTRY_ICON_SECONDARY
const EXPANDER_COLLAPSED = C.GTK_EXPANDER_COLLAPSED
const EXPANDER_SEMI_COLLAPSED = C.GTK_EXPANDER_SEMI_COLLAPSED
const EXPANDER_SEMI_EXPANDED = C.GTK_EXPANDER_SEMI_EXPANDED
const EXPANDER_EXPANDED = C.GTK_EXPANDER_EXPANDED
const FILE_CHOOSER_ACTION_OPEN = C.GTK_FILE_CHOOSER_ACTION_OPEN
const FILE_CHOOSER_ACTION_SAVE = C.GTK_FILE_CHOOSER_ACTION_SAVE
const FILE_CHOOSER_ACTION_SELECT_FOLDER = C.GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER
const FILE_CHOOSER_ACTION_CREATE_FOLDER = C.GTK_FILE_CHOOSER_ACTION_CREATE_FOLDER
const FILE_CHOOSER_CONFIRMATION_CONFIRM = C.GTK_FILE_CHOOSER_CONFIRMATION_CONFIRM
const FILE_CHOOSER_CONFIRMATION_ACCEPT_FILENAME = C.GTK_FILE_CHOOSER_CONFIRMATION_ACCEPT_FILENAME
const FILE_CHOOSER_CONFIRMATION_SELECT_AGAIN = C.GTK_FILE_CHOOSER_CONFIRMATION_SELECT_AGAIN
const FILE_CHOOSER_ERROR_NONEXISTENT = C.GTK_FILE_CHOOSER_ERROR_NONEXISTENT
const FILE_CHOOSER_ERROR_BAD_FILENAME = C.GTK_FILE_CHOOSER_ERROR_BAD_FILENAME
const FILE_CHOOSER_ERROR_ALREADY_EXISTS = C.GTK_FILE_CHOOSER_ERROR_ALREADY_EXISTS
const FILE_CHOOSER_ERROR_INCOMPLETE_HOSTNAME = C.GTK_FILE_CHOOSER_ERROR_INCOMPLETE_HOSTNAME
const IM_PREEDIT_NOTHING = C.GTK_IM_PREEDIT_NOTHING
const IM_PREEDIT_CALLBACK = C.GTK_IM_PREEDIT_CALLBACK
const IM_PREEDIT_NONE = C.GTK_IM_PREEDIT_NONE
const IM_STATUS_NOTHING = C.GTK_IM_STATUS_NOTHING
const IM_STATUS_CALLBACK = C.GTK_IM_STATUS_CALLBACK
const IM_STATUS_NONE = C.GTK_IM_STATUS_NONE
const ICON_SIZE_INVALID = C.GTK_ICON_SIZE_INVALID
const ICON_SIZE_MENU = C.GTK_ICON_SIZE_MENU
const ICON_SIZE_SMALL_TOOLBAR = C.GTK_ICON_SIZE_SMALL_TOOLBAR
const ICON_SIZE_LARGE_TOOLBAR = C.GTK_ICON_SIZE_LARGE_TOOLBAR
const ICON_SIZE_BUTTON = C.GTK_ICON_SIZE_BUTTON
const ICON_SIZE_DND = C.GTK_ICON_SIZE_DND
const ICON_SIZE_DIALOG = C.GTK_ICON_SIZE_DIALOG
const ICON_THEME_NOT_FOUND = C.GTK_ICON_THEME_NOT_FOUND
const ICON_THEME_FAILED = C.GTK_ICON_THEME_FAILED
const ICON_VIEW_NO_DROP = C.GTK_ICON_VIEW_NO_DROP
const ICON_VIEW_DROP_INTO = C.GTK_ICON_VIEW_DROP_INTO
const ICON_VIEW_DROP_LEFT = C.GTK_ICON_VIEW_DROP_LEFT
const ICON_VIEW_DROP_RIGHT = C.GTK_ICON_VIEW_DROP_RIGHT
const ICON_VIEW_DROP_ABOVE = C.GTK_ICON_VIEW_DROP_ABOVE
const ICON_VIEW_DROP_BELOW = C.GTK_ICON_VIEW_DROP_BELOW
const IMAGE_EMPTY = C.GTK_IMAGE_EMPTY
const IMAGE_PIXBUF = C.GTK_IMAGE_PIXBUF
const IMAGE_STOCK = C.GTK_IMAGE_STOCK
const IMAGE_ICON_SET = C.GTK_IMAGE_ICON_SET
const IMAGE_ANIMATION = C.GTK_IMAGE_ANIMATION
const IMAGE_ICON_NAME = C.GTK_IMAGE_ICON_NAME
const IMAGE_GICON = C.GTK_IMAGE_GICON
const INPUT_PURPOSE_FREE_FORM = C.GTK_INPUT_PURPOSE_FREE_FORM
const INPUT_PURPOSE_ALPHA = C.GTK_INPUT_PURPOSE_ALPHA
const INPUT_PURPOSE_DIGITS = C.GTK_INPUT_PURPOSE_DIGITS
const INPUT_PURPOSE_NUMBER = C.GTK_INPUT_PURPOSE_NUMBER
const INPUT_PURPOSE_PHONE = C.GTK_INPUT_PURPOSE_PHONE
const INPUT_PURPOSE_URL = C.GTK_INPUT_PURPOSE_URL
const INPUT_PURPOSE_EMAIL = C.GTK_INPUT_PURPOSE_EMAIL
const INPUT_PURPOSE_NAME = C.GTK_INPUT_PURPOSE_NAME
const INPUT_PURPOSE_PASSWORD = C.GTK_INPUT_PURPOSE_PASSWORD
const INPUT_PURPOSE_PIN = C.GTK_INPUT_PURPOSE_PIN
const JUSTIFY_LEFT = C.GTK_JUSTIFY_LEFT
const JUSTIFY_RIGHT = C.GTK_JUSTIFY_RIGHT
const JUSTIFY_CENTER = C.GTK_JUSTIFY_CENTER
const JUSTIFY_FILL = C.GTK_JUSTIFY_FILL
const LEVEL_BAR_MODE_CONTINUOUS = C.GTK_LEVEL_BAR_MODE_CONTINUOUS
const LEVEL_BAR_MODE_DISCRETE = C.GTK_LEVEL_BAR_MODE_DISCRETE
const LICENSE_UNKNOWN = C.GTK_LICENSE_UNKNOWN
const LICENSE_CUSTOM = C.GTK_LICENSE_CUSTOM
const LICENSE_GPL_2_0 = C.GTK_LICENSE_GPL_2_0
const LICENSE_GPL_3_0 = C.GTK_LICENSE_GPL_3_0
const LICENSE_LGPL_2_1 = C.GTK_LICENSE_LGPL_2_1
const LICENSE_LGPL_3_0 = C.GTK_LICENSE_LGPL_3_0
const LICENSE_BSD = C.GTK_LICENSE_BSD
const LICENSE_MIT_X11 = C.GTK_LICENSE_MIT_X11
const LICENSE_ARTISTIC = C.GTK_LICENSE_ARTISTIC
const MENU_DIR_PARENT = C.GTK_MENU_DIR_PARENT
const MENU_DIR_CHILD = C.GTK_MENU_DIR_CHILD
const MENU_DIR_NEXT = C.GTK_MENU_DIR_NEXT
const MENU_DIR_PREV = C.GTK_MENU_DIR_PREV
const MESSAGE_INFO = C.GTK_MESSAGE_INFO
const MESSAGE_WARNING = C.GTK_MESSAGE_WARNING
const MESSAGE_QUESTION = C.GTK_MESSAGE_QUESTION
const MESSAGE_ERROR = C.GTK_MESSAGE_ERROR
const MESSAGE_OTHER = C.GTK_MESSAGE_OTHER
const MOVEMENT_LOGICAL_POSITIONS = C.GTK_MOVEMENT_LOGICAL_POSITIONS
const MOVEMENT_VISUAL_POSITIONS = C.GTK_MOVEMENT_VISUAL_POSITIONS
const MOVEMENT_WORDS = C.GTK_MOVEMENT_WORDS
const MOVEMENT_DISPLAY_LINES = C.GTK_MOVEMENT_DISPLAY_LINES
const MOVEMENT_DISPLAY_LINE_ENDS = C.GTK_MOVEMENT_DISPLAY_LINE_ENDS
const MOVEMENT_PARAGRAPHS = C.GTK_MOVEMENT_PARAGRAPHS
const MOVEMENT_PARAGRAPH_ENDS = C.GTK_MOVEMENT_PARAGRAPH_ENDS
const MOVEMENT_PAGES = C.GTK_MOVEMENT_PAGES
const MOVEMENT_BUFFER_ENDS = C.GTK_MOVEMENT_BUFFER_ENDS
const MOVEMENT_HORIZONTAL_PAGES = C.GTK_MOVEMENT_HORIZONTAL_PAGES
const NOTEBOOK_TAB_FIRST = C.GTK_NOTEBOOK_TAB_FIRST
const NOTEBOOK_TAB_LAST = C.GTK_NOTEBOOK_TAB_LAST
const NUMBER_UP_LAYOUT_LEFT_TO_RIGHT_TOP_TO_BOTTOM = C.GTK_NUMBER_UP_LAYOUT_LEFT_TO_RIGHT_TOP_TO_BOTTOM
const NUMBER_UP_LAYOUT_LEFT_TO_RIGHT_BOTTOM_TO_TOP = C.GTK_NUMBER_UP_LAYOUT_LEFT_TO_RIGHT_BOTTOM_TO_TOP
const NUMBER_UP_LAYOUT_RIGHT_TO_LEFT_TOP_TO_BOTTOM = C.GTK_NUMBER_UP_LAYOUT_RIGHT_TO_LEFT_TOP_TO_BOTTOM
const NUMBER_UP_LAYOUT_RIGHT_TO_LEFT_BOTTOM_TO_TOP = C.GTK_NUMBER_UP_LAYOUT_RIGHT_TO_LEFT_BOTTOM_TO_TOP
const NUMBER_UP_LAYOUT_TOP_TO_BOTTOM_LEFT_TO_RIGHT = C.GTK_NUMBER_UP_LAYOUT_TOP_TO_BOTTOM_LEFT_TO_RIGHT
const NUMBER_UP_LAYOUT_TOP_TO_BOTTOM_RIGHT_TO_LEFT = C.GTK_NUMBER_UP_LAYOUT_TOP_TO_BOTTOM_RIGHT_TO_LEFT
const NUMBER_UP_LAYOUT_BOTTOM_TO_TOP_LEFT_TO_RIGHT = C.GTK_NUMBER_UP_LAYOUT_BOTTOM_TO_TOP_LEFT_TO_RIGHT
const NUMBER_UP_LAYOUT_BOTTOM_TO_TOP_RIGHT_TO_LEFT = C.GTK_NUMBER_UP_LAYOUT_BOTTOM_TO_TOP_RIGHT_TO_LEFT
const ORIENTATION_HORIZONTAL = C.GTK_ORIENTATION_HORIZONTAL
const ORIENTATION_VERTICAL = C.GTK_ORIENTATION_VERTICAL
const PACK_DIRECTION_LTR = C.GTK_PACK_DIRECTION_LTR
const PACK_DIRECTION_RTL = C.GTK_PACK_DIRECTION_RTL
const PACK_DIRECTION_TTB = C.GTK_PACK_DIRECTION_TTB
const PACK_DIRECTION_BTT = C.GTK_PACK_DIRECTION_BTT
const PACK_START = C.GTK_PACK_START
const PACK_END = C.GTK_PACK_END
const PAGE_ORIENTATION_PORTRAIT = C.GTK_PAGE_ORIENTATION_PORTRAIT
const PAGE_ORIENTATION_LANDSCAPE = C.GTK_PAGE_ORIENTATION_LANDSCAPE
const PAGE_ORIENTATION_REVERSE_PORTRAIT = C.GTK_PAGE_ORIENTATION_REVERSE_PORTRAIT
const PAGE_ORIENTATION_REVERSE_LANDSCAPE = C.GTK_PAGE_ORIENTATION_REVERSE_LANDSCAPE
const PAGE_SET_ALL = C.GTK_PAGE_SET_ALL
const PAGE_SET_EVEN = C.GTK_PAGE_SET_EVEN
const PAGE_SET_ODD = C.GTK_PAGE_SET_ODD
const PATH_PRIO_LOWEST = C.GTK_PATH_PRIO_LOWEST
const PATH_PRIO_GTK = C.GTK_PATH_PRIO_GTK
const PATH_PRIO_APPLICATION = C.GTK_PATH_PRIO_APPLICATION
const PATH_PRIO_THEME = C.GTK_PATH_PRIO_THEME
const PATH_PRIO_RC = C.GTK_PATH_PRIO_RC
const PATH_PRIO_HIGHEST = C.GTK_PATH_PRIO_HIGHEST
const PATH_WIDGET = C.GTK_PATH_WIDGET
const PATH_WIDGET_CLASS = C.GTK_PATH_WIDGET_CLASS
const PATH_CLASS = C.GTK_PATH_CLASS
const POLICY_ALWAYS = C.GTK_POLICY_ALWAYS
const POLICY_AUTOMATIC = C.GTK_POLICY_AUTOMATIC
const POLICY_NEVER = C.GTK_POLICY_NEVER
const POS_LEFT = C.GTK_POS_LEFT
const POS_RIGHT = C.GTK_POS_RIGHT
const POS_TOP = C.GTK_POS_TOP
const POS_BOTTOM = C.GTK_POS_BOTTOM
const PRINT_DUPLEX_SIMPLEX = C.GTK_PRINT_DUPLEX_SIMPLEX
const PRINT_DUPLEX_HORIZONTAL = C.GTK_PRINT_DUPLEX_HORIZONTAL
const PRINT_DUPLEX_VERTICAL = C.GTK_PRINT_DUPLEX_VERTICAL
const PRINT_ERROR_GENERAL = C.GTK_PRINT_ERROR_GENERAL
const PRINT_ERROR_INTERNAL_ERROR = C.GTK_PRINT_ERROR_INTERNAL_ERROR
const PRINT_ERROR_NOMEM = C.GTK_PRINT_ERROR_NOMEM
const PRINT_ERROR_INVALID_FILE = C.GTK_PRINT_ERROR_INVALID_FILE
const PRINT_OPERATION_ACTION_PRINT_DIALOG = C.GTK_PRINT_OPERATION_ACTION_PRINT_DIALOG
const PRINT_OPERATION_ACTION_PRINT = C.GTK_PRINT_OPERATION_ACTION_PRINT
const PRINT_OPERATION_ACTION_PREVIEW = C.GTK_PRINT_OPERATION_ACTION_PREVIEW
const PRINT_OPERATION_ACTION_EXPORT = C.GTK_PRINT_OPERATION_ACTION_EXPORT
const PRINT_OPERATION_RESULT_ERROR = C.GTK_PRINT_OPERATION_RESULT_ERROR
const PRINT_OPERATION_RESULT_APPLY = C.GTK_PRINT_OPERATION_RESULT_APPLY
const PRINT_OPERATION_RESULT_CANCEL = C.GTK_PRINT_OPERATION_RESULT_CANCEL
const PRINT_OPERATION_RESULT_IN_PROGRESS = C.GTK_PRINT_OPERATION_RESULT_IN_PROGRESS
const PRINT_PAGES_ALL = C.GTK_PRINT_PAGES_ALL
const PRINT_PAGES_CURRENT = C.GTK_PRINT_PAGES_CURRENT
const PRINT_PAGES_RANGES = C.GTK_PRINT_PAGES_RANGES
const PRINT_PAGES_SELECTION = C.GTK_PRINT_PAGES_SELECTION
const PRINT_QUALITY_LOW = C.GTK_PRINT_QUALITY_LOW
const PRINT_QUALITY_NORMAL = C.GTK_PRINT_QUALITY_NORMAL
const PRINT_QUALITY_HIGH = C.GTK_PRINT_QUALITY_HIGH
const PRINT_QUALITY_DRAFT = C.GTK_PRINT_QUALITY_DRAFT
const PRINT_STATUS_INITIAL = C.GTK_PRINT_STATUS_INITIAL
const PRINT_STATUS_PREPARING = C.GTK_PRINT_STATUS_PREPARING
const PRINT_STATUS_GENERATING_DATA = C.GTK_PRINT_STATUS_GENERATING_DATA
const PRINT_STATUS_SENDING_DATA = C.GTK_PRINT_STATUS_SENDING_DATA
const PRINT_STATUS_PENDING = C.GTK_PRINT_STATUS_PENDING
const PRINT_STATUS_PENDING_ISSUE = C.GTK_PRINT_STATUS_PENDING_ISSUE
const PRINT_STATUS_PRINTING = C.GTK_PRINT_STATUS_PRINTING
const PRINT_STATUS_FINISHED = C.GTK_PRINT_STATUS_FINISHED
const PRINT_STATUS_FINISHED_ABORTED = C.GTK_PRINT_STATUS_FINISHED_ABORTED
const RC_TOKEN_INVALID = C.GTK_RC_TOKEN_INVALID
const RC_TOKEN_INCLUDE = C.GTK_RC_TOKEN_INCLUDE
const RC_TOKEN_NORMAL = C.GTK_RC_TOKEN_NORMAL
const RC_TOKEN_ACTIVE = C.GTK_RC_TOKEN_ACTIVE
const RC_TOKEN_PRELIGHT = C.GTK_RC_TOKEN_PRELIGHT
const RC_TOKEN_SELECTED = C.GTK_RC_TOKEN_SELECTED
const RC_TOKEN_INSENSITIVE = C.GTK_RC_TOKEN_INSENSITIVE
const RC_TOKEN_FG = C.GTK_RC_TOKEN_FG
const RC_TOKEN_BG = C.GTK_RC_TOKEN_BG
const RC_TOKEN_TEXT = C.GTK_RC_TOKEN_TEXT
const RC_TOKEN_BASE = C.GTK_RC_TOKEN_BASE
const RC_TOKEN_XTHICKNESS = C.GTK_RC_TOKEN_XTHICKNESS
const RC_TOKEN_YTHICKNESS = C.GTK_RC_TOKEN_YTHICKNESS
const RC_TOKEN_FONT = C.GTK_RC_TOKEN_FONT
const RC_TOKEN_FONTSET = C.GTK_RC_TOKEN_FONTSET
const RC_TOKEN_FONT_NAME = C.GTK_RC_TOKEN_FONT_NAME
const RC_TOKEN_BG_PIXMAP = C.GTK_RC_TOKEN_BG_PIXMAP
const RC_TOKEN_PIXMAP_PATH = C.GTK_RC_TOKEN_PIXMAP_PATH
const RC_TOKEN_STYLE = C.GTK_RC_TOKEN_STYLE
const RC_TOKEN_BINDING = C.GTK_RC_TOKEN_BINDING
const RC_TOKEN_BIND = C.GTK_RC_TOKEN_BIND
const RC_TOKEN_WIDGET = C.GTK_RC_TOKEN_WIDGET
const RC_TOKEN_WIDGET_CLASS = C.GTK_RC_TOKEN_WIDGET_CLASS
const RC_TOKEN_CLASS = C.GTK_RC_TOKEN_CLASS
const RC_TOKEN_LOWEST = C.GTK_RC_TOKEN_LOWEST
const RC_TOKEN_GTK = C.GTK_RC_TOKEN_GTK
const RC_TOKEN_APPLICATION = C.GTK_RC_TOKEN_APPLICATION
const RC_TOKEN_THEME = C.GTK_RC_TOKEN_THEME
const RC_TOKEN_RC = C.GTK_RC_TOKEN_RC
const RC_TOKEN_HIGHEST = C.GTK_RC_TOKEN_HIGHEST
const RC_TOKEN_ENGINE = C.GTK_RC_TOKEN_ENGINE
const RC_TOKEN_MODULE_PATH = C.GTK_RC_TOKEN_MODULE_PATH
const RC_TOKEN_IM_MODULE_PATH = C.GTK_RC_TOKEN_IM_MODULE_PATH
const RC_TOKEN_IM_MODULE_FILE = C.GTK_RC_TOKEN_IM_MODULE_FILE
const RC_TOKEN_STOCK = C.GTK_RC_TOKEN_STOCK
const RC_TOKEN_LTR = C.GTK_RC_TOKEN_LTR
const RC_TOKEN_RTL = C.GTK_RC_TOKEN_RTL
const RC_TOKEN_COLOR = C.GTK_RC_TOKEN_COLOR
const RC_TOKEN_UNBIND = C.GTK_RC_TOKEN_UNBIND
const RC_TOKEN_LAST = C.GTK_RC_TOKEN_LAST
const RECENT_CHOOSER_ERROR_NOT_FOUND = C.GTK_RECENT_CHOOSER_ERROR_NOT_FOUND
const RECENT_CHOOSER_ERROR_INVALID_URI = C.GTK_RECENT_CHOOSER_ERROR_INVALID_URI
const RECENT_MANAGER_ERROR_NOT_FOUND = C.GTK_RECENT_MANAGER_ERROR_NOT_FOUND
const RECENT_MANAGER_ERROR_INVALID_URI = C.GTK_RECENT_MANAGER_ERROR_INVALID_URI
const RECENT_MANAGER_ERROR_INVALID_ENCODING = C.GTK_RECENT_MANAGER_ERROR_INVALID_ENCODING
const RECENT_MANAGER_ERROR_NOT_REGISTERED = C.GTK_RECENT_MANAGER_ERROR_NOT_REGISTERED
const RECENT_MANAGER_ERROR_READ = C.GTK_RECENT_MANAGER_ERROR_READ
const RECENT_MANAGER_ERROR_WRITE = C.GTK_RECENT_MANAGER_ERROR_WRITE
const RECENT_MANAGER_ERROR_UNKNOWN = C.GTK_RECENT_MANAGER_ERROR_UNKNOWN
const RECENT_SORT_NONE = C.GTK_RECENT_SORT_NONE
const RECENT_SORT_MRU = C.GTK_RECENT_SORT_MRU
const RECENT_SORT_LRU = C.GTK_RECENT_SORT_LRU
const RECENT_SORT_CUSTOM = C.GTK_RECENT_SORT_CUSTOM
const RELIEF_NORMAL = C.GTK_RELIEF_NORMAL
const RELIEF_HALF = C.GTK_RELIEF_HALF
const RELIEF_NONE = C.GTK_RELIEF_NONE
const RESIZE_PARENT = C.GTK_RESIZE_PARENT
const RESIZE_QUEUE = C.GTK_RESIZE_QUEUE
const RESIZE_IMMEDIATE = C.GTK_RESIZE_IMMEDIATE
const RESPONSE_NONE = C.GTK_RESPONSE_NONE
const RESPONSE_REJECT = C.GTK_RESPONSE_REJECT
const RESPONSE_ACCEPT = C.GTK_RESPONSE_ACCEPT
const RESPONSE_DELETE_EVENT = C.GTK_RESPONSE_DELETE_EVENT
const RESPONSE_OK = C.GTK_RESPONSE_OK
const RESPONSE_CANCEL = C.GTK_RESPONSE_CANCEL
const RESPONSE_CLOSE = C.GTK_RESPONSE_CLOSE
const RESPONSE_YES = C.GTK_RESPONSE_YES
const RESPONSE_NO = C.GTK_RESPONSE_NO
const RESPONSE_APPLY = C.GTK_RESPONSE_APPLY
const RESPONSE_HELP = C.GTK_RESPONSE_HELP
const SCROLL_STEPS = C.GTK_SCROLL_STEPS
const SCROLL_PAGES = C.GTK_SCROLL_PAGES
const SCROLL_ENDS = C.GTK_SCROLL_ENDS
const SCROLL_HORIZONTAL_STEPS = C.GTK_SCROLL_HORIZONTAL_STEPS
const SCROLL_HORIZONTAL_PAGES = C.GTK_SCROLL_HORIZONTAL_PAGES
const SCROLL_HORIZONTAL_ENDS = C.GTK_SCROLL_HORIZONTAL_ENDS
const SCROLL_NONE = C.GTK_SCROLL_NONE
const SCROLL_JUMP = C.GTK_SCROLL_JUMP
const SCROLL_STEP_BACKWARD = C.GTK_SCROLL_STEP_BACKWARD
const SCROLL_STEP_FORWARD = C.GTK_SCROLL_STEP_FORWARD
const SCROLL_PAGE_BACKWARD = C.GTK_SCROLL_PAGE_BACKWARD
const SCROLL_PAGE_FORWARD = C.GTK_SCROLL_PAGE_FORWARD
const SCROLL_STEP_UP = C.GTK_SCROLL_STEP_UP
const SCROLL_STEP_DOWN = C.GTK_SCROLL_STEP_DOWN
const SCROLL_PAGE_UP = C.GTK_SCROLL_PAGE_UP
const SCROLL_PAGE_DOWN = C.GTK_SCROLL_PAGE_DOWN
const SCROLL_STEP_LEFT = C.GTK_SCROLL_STEP_LEFT
const SCROLL_STEP_RIGHT = C.GTK_SCROLL_STEP_RIGHT
const SCROLL_PAGE_LEFT = C.GTK_SCROLL_PAGE_LEFT
const SCROLL_PAGE_RIGHT = C.GTK_SCROLL_PAGE_RIGHT
const SCROLL_START = C.GTK_SCROLL_START
const SCROLL_END = C.GTK_SCROLL_END
const SCROLL_MINIMUM = C.GTK_SCROLL_MINIMUM
const SCROLL_NATURAL = C.GTK_SCROLL_NATURAL
const SELECTION_NONE = C.GTK_SELECTION_NONE
const SELECTION_SINGLE = C.GTK_SELECTION_SINGLE
const SELECTION_BROWSE = C.GTK_SELECTION_BROWSE
const SELECTION_MULTIPLE = C.GTK_SELECTION_MULTIPLE
const SENSITIVITY_AUTO = C.GTK_SENSITIVITY_AUTO
const SENSITIVITY_ON = C.GTK_SENSITIVITY_ON
const SENSITIVITY_OFF = C.GTK_SENSITIVITY_OFF
const SHADOW_NONE = C.GTK_SHADOW_NONE
const SHADOW_IN = C.GTK_SHADOW_IN
const SHADOW_OUT = C.GTK_SHADOW_OUT
const SHADOW_ETCHED_IN = C.GTK_SHADOW_ETCHED_IN
const SHADOW_ETCHED_OUT = C.GTK_SHADOW_ETCHED_OUT
const SIZE_GROUP_NONE = C.GTK_SIZE_GROUP_NONE
const SIZE_GROUP_HORIZONTAL = C.GTK_SIZE_GROUP_HORIZONTAL
const SIZE_GROUP_VERTICAL = C.GTK_SIZE_GROUP_VERTICAL
const SIZE_GROUP_BOTH = C.GTK_SIZE_GROUP_BOTH
const SIZE_REQUEST_HEIGHT_FOR_WIDTH = C.GTK_SIZE_REQUEST_HEIGHT_FOR_WIDTH
const SIZE_REQUEST_WIDTH_FOR_HEIGHT = C.GTK_SIZE_REQUEST_WIDTH_FOR_HEIGHT
const SIZE_REQUEST_CONSTANT_SIZE = C.GTK_SIZE_REQUEST_CONSTANT_SIZE
const SORT_ASCENDING = C.GTK_SORT_ASCENDING
const SORT_DESCENDING = C.GTK_SORT_DESCENDING
const UPDATE_ALWAYS = C.GTK_UPDATE_ALWAYS
const UPDATE_IF_VALID = C.GTK_UPDATE_IF_VALID
const SPIN_STEP_FORWARD = C.GTK_SPIN_STEP_FORWARD
const SPIN_STEP_BACKWARD = C.GTK_SPIN_STEP_BACKWARD
const SPIN_PAGE_FORWARD = C.GTK_SPIN_PAGE_FORWARD
const SPIN_PAGE_BACKWARD = C.GTK_SPIN_PAGE_BACKWARD
const SPIN_HOME = C.GTK_SPIN_HOME
const SPIN_END = C.GTK_SPIN_END
const SPIN_USER_DEFINED = C.GTK_SPIN_USER_DEFINED
const STATE_NORMAL = C.GTK_STATE_NORMAL
const STATE_ACTIVE = C.GTK_STATE_ACTIVE
const STATE_PRELIGHT = C.GTK_STATE_PRELIGHT
const STATE_SELECTED = C.GTK_STATE_SELECTED
const STATE_INSENSITIVE = C.GTK_STATE_INSENSITIVE
const STATE_INCONSISTENT = C.GTK_STATE_INCONSISTENT
const STATE_FOCUSED = C.GTK_STATE_FOCUSED
const TEXT_BUFFER_TARGET_INFO_BUFFER_CONTENTS = C.GTK_TEXT_BUFFER_TARGET_INFO_BUFFER_CONTENTS
const TEXT_BUFFER_TARGET_INFO_RICH_TEXT = C.GTK_TEXT_BUFFER_TARGET_INFO_RICH_TEXT
const TEXT_BUFFER_TARGET_INFO_TEXT = C.GTK_TEXT_BUFFER_TARGET_INFO_TEXT
const TEXT_DIR_NONE = C.GTK_TEXT_DIR_NONE
const TEXT_DIR_LTR = C.GTK_TEXT_DIR_LTR
const TEXT_DIR_RTL = C.GTK_TEXT_DIR_RTL
const TEXT_WINDOW_PRIVATE = C.GTK_TEXT_WINDOW_PRIVATE
const TEXT_WINDOW_WIDGET = C.GTK_TEXT_WINDOW_WIDGET
const TEXT_WINDOW_TEXT = C.GTK_TEXT_WINDOW_TEXT
const TEXT_WINDOW_LEFT = C.GTK_TEXT_WINDOW_LEFT
const TEXT_WINDOW_RIGHT = C.GTK_TEXT_WINDOW_RIGHT
const TEXT_WINDOW_TOP = C.GTK_TEXT_WINDOW_TOP
const TEXT_WINDOW_BOTTOM = C.GTK_TEXT_WINDOW_BOTTOM
const TOOLBAR_SPACE_EMPTY = C.GTK_TOOLBAR_SPACE_EMPTY
const TOOLBAR_SPACE_LINE = C.GTK_TOOLBAR_SPACE_LINE
const TOOLBAR_ICONS = C.GTK_TOOLBAR_ICONS
const TOOLBAR_TEXT = C.GTK_TOOLBAR_TEXT
const TOOLBAR_BOTH = C.GTK_TOOLBAR_BOTH
const TOOLBAR_BOTH_HORIZ = C.GTK_TOOLBAR_BOTH_HORIZ
const TREE_VIEW_COLUMN_GROW_ONLY = C.GTK_TREE_VIEW_COLUMN_GROW_ONLY
const TREE_VIEW_COLUMN_AUTOSIZE = C.GTK_TREE_VIEW_COLUMN_AUTOSIZE
const TREE_VIEW_COLUMN_FIXED = C.GTK_TREE_VIEW_COLUMN_FIXED
const TREE_VIEW_DROP_BEFORE = C.GTK_TREE_VIEW_DROP_BEFORE
const TREE_VIEW_DROP_AFTER = C.GTK_TREE_VIEW_DROP_AFTER
const TREE_VIEW_DROP_INTO_OR_BEFORE = C.GTK_TREE_VIEW_DROP_INTO_OR_BEFORE
const TREE_VIEW_DROP_INTO_OR_AFTER = C.GTK_TREE_VIEW_DROP_INTO_OR_AFTER
const TREE_VIEW_GRID_LINES_NONE = C.GTK_TREE_VIEW_GRID_LINES_NONE
const TREE_VIEW_GRID_LINES_HORIZONTAL = C.GTK_TREE_VIEW_GRID_LINES_HORIZONTAL
const TREE_VIEW_GRID_LINES_VERTICAL = C.GTK_TREE_VIEW_GRID_LINES_VERTICAL
const TREE_VIEW_GRID_LINES_BOTH = C.GTK_TREE_VIEW_GRID_LINES_BOTH
const UNIT_NONE = C.GTK_UNIT_NONE
const UNIT_POINTS = C.GTK_UNIT_POINTS
const UNIT_INCH = C.GTK_UNIT_INCH
const UNIT_MM = C.GTK_UNIT_MM
const WIDGET_HELP_TOOLTIP = C.GTK_WIDGET_HELP_TOOLTIP
const WIDGET_HELP_WHATS_THIS = C.GTK_WIDGET_HELP_WHATS_THIS
const WIN_POS_NONE = C.GTK_WIN_POS_NONE
const WIN_POS_CENTER = C.GTK_WIN_POS_CENTER
const WIN_POS_MOUSE = C.GTK_WIN_POS_MOUSE
const WIN_POS_CENTER_ALWAYS = C.GTK_WIN_POS_CENTER_ALWAYS
const WIN_POS_CENTER_ON_PARENT = C.GTK_WIN_POS_CENTER_ON_PARENT
const WINDOW_TOPLEVEL = C.GTK_WINDOW_TOPLEVEL
const WINDOW_POPUP = C.GTK_WINDOW_POPUP
const WRAP_NONE = C.GTK_WRAP_NONE
const WRAP_CHAR = C.GTK_WRAP_CHAR
const WRAP_WORD = C.GTK_WRAP_WORD
const WRAP_WORD_CHAR = C.GTK_WRAP_WORD_CHAR
const BINARY_AGE = C.GTK_BINARY_AGE
const INPUT_ERROR = C.GTK_INPUT_ERROR
const INTERFACE_AGE = C.GTK_INTERFACE_AGE
const LEVEL_BAR_OFFSET_HIGH = C.GTK_LEVEL_BAR_OFFSET_HIGH
const LEVEL_BAR_OFFSET_LOW = C.GTK_LEVEL_BAR_OFFSET_LOW
const MAJOR_VERSION = C.GTK_MAJOR_VERSION
const MAX_COMPOSE_LEN = C.GTK_MAX_COMPOSE_LEN
const MICRO_VERSION = C.GTK_MICRO_VERSION
const MINOR_VERSION = C.GTK_MINOR_VERSION
const PAPER_NAME_A3 = C.GTK_PAPER_NAME_A3
const PAPER_NAME_A4 = C.GTK_PAPER_NAME_A4
const PAPER_NAME_A5 = C.GTK_PAPER_NAME_A5
const PAPER_NAME_B5 = C.GTK_PAPER_NAME_B5
const PAPER_NAME_EXECUTIVE = C.GTK_PAPER_NAME_EXECUTIVE
const PAPER_NAME_LEGAL = C.GTK_PAPER_NAME_LEGAL
const PAPER_NAME_LETTER = C.GTK_PAPER_NAME_LETTER
const PATH_PRIO_MASK = C.GTK_PATH_PRIO_MASK
const PRINT_SETTINGS_COLLATE = C.GTK_PRINT_SETTINGS_COLLATE
const PRINT_SETTINGS_DEFAULT_SOURCE = C.GTK_PRINT_SETTINGS_DEFAULT_SOURCE
const PRINT_SETTINGS_DITHER = C.GTK_PRINT_SETTINGS_DITHER
const PRINT_SETTINGS_DUPLEX = C.GTK_PRINT_SETTINGS_DUPLEX
const PRINT_SETTINGS_FINISHINGS = C.GTK_PRINT_SETTINGS_FINISHINGS
const PRINT_SETTINGS_MEDIA_TYPE = C.GTK_PRINT_SETTINGS_MEDIA_TYPE
const PRINT_SETTINGS_NUMBER_UP = C.GTK_PRINT_SETTINGS_NUMBER_UP
const PRINT_SETTINGS_NUMBER_UP_LAYOUT = C.GTK_PRINT_SETTINGS_NUMBER_UP_LAYOUT
const PRINT_SETTINGS_N_COPIES = C.GTK_PRINT_SETTINGS_N_COPIES
const PRINT_SETTINGS_ORIENTATION = C.GTK_PRINT_SETTINGS_ORIENTATION
const PRINT_SETTINGS_OUTPUT_BASENAME = C.GTK_PRINT_SETTINGS_OUTPUT_BASENAME
const PRINT_SETTINGS_OUTPUT_BIN = C.GTK_PRINT_SETTINGS_OUTPUT_BIN
const PRINT_SETTINGS_OUTPUT_DIR = C.GTK_PRINT_SETTINGS_OUTPUT_DIR
const PRINT_SETTINGS_OUTPUT_FILE_FORMAT = C.GTK_PRINT_SETTINGS_OUTPUT_FILE_FORMAT
const PRINT_SETTINGS_OUTPUT_URI = C.GTK_PRINT_SETTINGS_OUTPUT_URI
const PRINT_SETTINGS_PAGE_RANGES = C.GTK_PRINT_SETTINGS_PAGE_RANGES
const PRINT_SETTINGS_PAGE_SET = C.GTK_PRINT_SETTINGS_PAGE_SET
const PRINT_SETTINGS_PAPER_FORMAT = C.GTK_PRINT_SETTINGS_PAPER_FORMAT
const PRINT_SETTINGS_PAPER_HEIGHT = C.GTK_PRINT_SETTINGS_PAPER_HEIGHT
const PRINT_SETTINGS_PAPER_WIDTH = C.GTK_PRINT_SETTINGS_PAPER_WIDTH
const PRINT_SETTINGS_PRINTER = C.GTK_PRINT_SETTINGS_PRINTER
const PRINT_SETTINGS_PRINTER_LPI = C.GTK_PRINT_SETTINGS_PRINTER_LPI
const PRINT_SETTINGS_PRINT_PAGES = C.GTK_PRINT_SETTINGS_PRINT_PAGES
const PRINT_SETTINGS_QUALITY = C.GTK_PRINT_SETTINGS_QUALITY
const PRINT_SETTINGS_RESOLUTION = C.GTK_PRINT_SETTINGS_RESOLUTION
const PRINT_SETTINGS_RESOLUTION_X = C.GTK_PRINT_SETTINGS_RESOLUTION_X
const PRINT_SETTINGS_RESOLUTION_Y = C.GTK_PRINT_SETTINGS_RESOLUTION_Y
const PRINT_SETTINGS_REVERSE = C.GTK_PRINT_SETTINGS_REVERSE
const PRINT_SETTINGS_SCALE = C.GTK_PRINT_SETTINGS_SCALE
const PRINT_SETTINGS_USE_COLOR = C.GTK_PRINT_SETTINGS_USE_COLOR
const PRINT_SETTINGS_WIN32_DRIVER_EXTRA = C.GTK_PRINT_SETTINGS_WIN32_DRIVER_EXTRA
const PRINT_SETTINGS_WIN32_DRIVER_VERSION = C.GTK_PRINT_SETTINGS_WIN32_DRIVER_VERSION
const PRIORITY_RESIZE = C.GTK_PRIORITY_RESIZE
const STOCK_ABOUT = C.GTK_STOCK_ABOUT
const STOCK_ADD = C.GTK_STOCK_ADD
const STOCK_APPLY = C.GTK_STOCK_APPLY
const STOCK_BOLD = C.GTK_STOCK_BOLD
const STOCK_CANCEL = C.GTK_STOCK_CANCEL
const STOCK_CAPS_LOCK_WARNING = C.GTK_STOCK_CAPS_LOCK_WARNING
const STOCK_CDROM = C.GTK_STOCK_CDROM
const STOCK_CLEAR = C.GTK_STOCK_CLEAR
const STOCK_CLOSE = C.GTK_STOCK_CLOSE
const STOCK_COLOR_PICKER = C.GTK_STOCK_COLOR_PICKER
const STOCK_CONNECT = C.GTK_STOCK_CONNECT
const STOCK_CONVERT = C.GTK_STOCK_CONVERT
const STOCK_COPY = C.GTK_STOCK_COPY
const STOCK_CUT = C.GTK_STOCK_CUT
const STOCK_DELETE = C.GTK_STOCK_DELETE
const STOCK_DIALOG_AUTHENTICATION = C.GTK_STOCK_DIALOG_AUTHENTICATION
const STOCK_DIALOG_ERROR = C.GTK_STOCK_DIALOG_ERROR
const STOCK_DIALOG_INFO = C.GTK_STOCK_DIALOG_INFO
const STOCK_DIALOG_QUESTION = C.GTK_STOCK_DIALOG_QUESTION
const STOCK_DIALOG_WARNING = C.GTK_STOCK_DIALOG_WARNING
const STOCK_DIRECTORY = C.GTK_STOCK_DIRECTORY
const STOCK_DISCARD = C.GTK_STOCK_DISCARD
const STOCK_DISCONNECT = C.GTK_STOCK_DISCONNECT
const STOCK_DND = C.GTK_STOCK_DND
const STOCK_DND_MULTIPLE = C.GTK_STOCK_DND_MULTIPLE
const STOCK_EDIT = C.GTK_STOCK_EDIT
const STOCK_EXECUTE = C.GTK_STOCK_EXECUTE
const STOCK_FILE = C.GTK_STOCK_FILE
const STOCK_FIND = C.GTK_STOCK_FIND
const STOCK_FIND_AND_REPLACE = C.GTK_STOCK_FIND_AND_REPLACE
const STOCK_FLOPPY = C.GTK_STOCK_FLOPPY
const STOCK_FULLSCREEN = C.GTK_STOCK_FULLSCREEN
const STOCK_GOTO_BOTTOM = C.GTK_STOCK_GOTO_BOTTOM
const STOCK_GOTO_FIRST = C.GTK_STOCK_GOTO_FIRST
const STOCK_GOTO_LAST = C.GTK_STOCK_GOTO_LAST
const STOCK_GOTO_TOP = C.GTK_STOCK_GOTO_TOP
const STOCK_GO_BACK = C.GTK_STOCK_GO_BACK
const STOCK_GO_DOWN = C.GTK_STOCK_GO_DOWN
const STOCK_GO_FORWARD = C.GTK_STOCK_GO_FORWARD
const STOCK_GO_UP = C.GTK_STOCK_GO_UP
const STOCK_HARDDISK = C.GTK_STOCK_HARDDISK
const STOCK_HELP = C.GTK_STOCK_HELP
const STOCK_HOME = C.GTK_STOCK_HOME
const STOCK_INDENT = C.GTK_STOCK_INDENT
const STOCK_INDEX = C.GTK_STOCK_INDEX
const STOCK_INFO = C.GTK_STOCK_INFO
const STOCK_ITALIC = C.GTK_STOCK_ITALIC
const STOCK_JUMP_TO = C.GTK_STOCK_JUMP_TO
const STOCK_JUSTIFY_CENTER = C.GTK_STOCK_JUSTIFY_CENTER
const STOCK_JUSTIFY_FILL = C.GTK_STOCK_JUSTIFY_FILL
const STOCK_JUSTIFY_LEFT = C.GTK_STOCK_JUSTIFY_LEFT
const STOCK_JUSTIFY_RIGHT = C.GTK_STOCK_JUSTIFY_RIGHT
const STOCK_LEAVE_FULLSCREEN = C.GTK_STOCK_LEAVE_FULLSCREEN
const STOCK_MEDIA_FORWARD = C.GTK_STOCK_MEDIA_FORWARD
const STOCK_MEDIA_NEXT = C.GTK_STOCK_MEDIA_NEXT
const STOCK_MEDIA_PAUSE = C.GTK_STOCK_MEDIA_PAUSE
const STOCK_MEDIA_PLAY = C.GTK_STOCK_MEDIA_PLAY
const STOCK_MEDIA_PREVIOUS = C.GTK_STOCK_MEDIA_PREVIOUS
const STOCK_MEDIA_RECORD = C.GTK_STOCK_MEDIA_RECORD
const STOCK_MEDIA_REWIND = C.GTK_STOCK_MEDIA_REWIND
const STOCK_MEDIA_STOP = C.GTK_STOCK_MEDIA_STOP
const STOCK_MISSING_IMAGE = C.GTK_STOCK_MISSING_IMAGE
const STOCK_NETWORK = C.GTK_STOCK_NETWORK
const STOCK_NEW = C.GTK_STOCK_NEW
const STOCK_NO = C.GTK_STOCK_NO
const STOCK_OK = C.GTK_STOCK_OK
const STOCK_OPEN = C.GTK_STOCK_OPEN
const STOCK_ORIENTATION_LANDSCAPE = C.GTK_STOCK_ORIENTATION_LANDSCAPE
const STOCK_ORIENTATION_PORTRAIT = C.GTK_STOCK_ORIENTATION_PORTRAIT
const STOCK_ORIENTATION_REVERSE_LANDSCAPE = C.GTK_STOCK_ORIENTATION_REVERSE_LANDSCAPE
const STOCK_ORIENTATION_REVERSE_PORTRAIT = C.GTK_STOCK_ORIENTATION_REVERSE_PORTRAIT
const STOCK_PAGE_SETUP = C.GTK_STOCK_PAGE_SETUP
const STOCK_PASTE = C.GTK_STOCK_PASTE
const STOCK_PREFERENCES = C.GTK_STOCK_PREFERENCES
const STOCK_PRINT = C.GTK_STOCK_PRINT
const STOCK_PRINT_ERROR = C.GTK_STOCK_PRINT_ERROR
const STOCK_PRINT_PAUSED = C.GTK_STOCK_PRINT_PAUSED
const STOCK_PRINT_PREVIEW = C.GTK_STOCK_PRINT_PREVIEW
const STOCK_PRINT_REPORT = C.GTK_STOCK_PRINT_REPORT
const STOCK_PRINT_WARNING = C.GTK_STOCK_PRINT_WARNING
const STOCK_PROPERTIES = C.GTK_STOCK_PROPERTIES
const STOCK_QUIT = C.GTK_STOCK_QUIT
const STOCK_REDO = C.GTK_STOCK_REDO
const STOCK_REFRESH = C.GTK_STOCK_REFRESH
const STOCK_REMOVE = C.GTK_STOCK_REMOVE
const STOCK_REVERT_TO_SAVED = C.GTK_STOCK_REVERT_TO_SAVED
const STOCK_SAVE = C.GTK_STOCK_SAVE
const STOCK_SAVE_AS = C.GTK_STOCK_SAVE_AS
const STOCK_SELECT_ALL = C.GTK_STOCK_SELECT_ALL
const STOCK_SELECT_COLOR = C.GTK_STOCK_SELECT_COLOR
const STOCK_SELECT_FONT = C.GTK_STOCK_SELECT_FONT
const STOCK_SORT_ASCENDING = C.GTK_STOCK_SORT_ASCENDING
const STOCK_SORT_DESCENDING = C.GTK_STOCK_SORT_DESCENDING
const STOCK_SPELL_CHECK = C.GTK_STOCK_SPELL_CHECK
const STOCK_STOP = C.GTK_STOCK_STOP
const STOCK_STRIKETHROUGH = C.GTK_STOCK_STRIKETHROUGH
const STOCK_UNDELETE = C.GTK_STOCK_UNDELETE
const STOCK_UNDERLINE = C.GTK_STOCK_UNDERLINE
const STOCK_UNDO = C.GTK_STOCK_UNDO
const STOCK_UNINDENT = C.GTK_STOCK_UNINDENT
const STOCK_YES = C.GTK_STOCK_YES
const STOCK_ZOOM_100 = C.GTK_STOCK_ZOOM_100
const STOCK_ZOOM_FIT = C.GTK_STOCK_ZOOM_FIT
const STOCK_ZOOM_IN = C.GTK_STOCK_ZOOM_IN
const STOCK_ZOOM_OUT = C.GTK_STOCK_ZOOM_OUT
const STYLE_CLASS_ACCELERATOR = C.GTK_STYLE_CLASS_ACCELERATOR
const STYLE_CLASS_ARROW = C.GTK_STYLE_CLASS_ARROW
const STYLE_CLASS_BACKGROUND = C.GTK_STYLE_CLASS_BACKGROUND
const STYLE_CLASS_BOTTOM = C.GTK_STYLE_CLASS_BOTTOM
const STYLE_CLASS_BUTTON = C.GTK_STYLE_CLASS_BUTTON
const STYLE_CLASS_CALENDAR = C.GTK_STYLE_CLASS_CALENDAR
const STYLE_CLASS_CELL = C.GTK_STYLE_CLASS_CELL
const STYLE_CLASS_CHECK = C.GTK_STYLE_CLASS_CHECK
const STYLE_CLASS_COMBOBOX_ENTRY = C.GTK_STYLE_CLASS_COMBOBOX_ENTRY
const STYLE_CLASS_CURSOR_HANDLE = C.GTK_STYLE_CLASS_CURSOR_HANDLE
const STYLE_CLASS_DEFAULT = C.GTK_STYLE_CLASS_DEFAULT
const STYLE_CLASS_DIM_LABEL = C.GTK_STYLE_CLASS_DIM_LABEL
const STYLE_CLASS_DND = C.GTK_STYLE_CLASS_DND
const STYLE_CLASS_DOCK = C.GTK_STYLE_CLASS_DOCK
const STYLE_CLASS_ENTRY = C.GTK_STYLE_CLASS_ENTRY
const STYLE_CLASS_ERROR = C.GTK_STYLE_CLASS_ERROR
const STYLE_CLASS_EXPANDER = C.GTK_STYLE_CLASS_EXPANDER
const STYLE_CLASS_FRAME = C.GTK_STYLE_CLASS_FRAME
const STYLE_CLASS_GRIP = C.GTK_STYLE_CLASS_GRIP
const STYLE_CLASS_HEADER = C.GTK_STYLE_CLASS_HEADER
const STYLE_CLASS_HIGHLIGHT = C.GTK_STYLE_CLASS_HIGHLIGHT
const STYLE_CLASS_HORIZONTAL = C.GTK_STYLE_CLASS_HORIZONTAL
const STYLE_CLASS_IMAGE = C.GTK_STYLE_CLASS_IMAGE
const STYLE_CLASS_INFO = C.GTK_STYLE_CLASS_INFO
const STYLE_CLASS_INLINE_TOOLBAR = C.GTK_STYLE_CLASS_INLINE_TOOLBAR
const STYLE_CLASS_LEFT = C.GTK_STYLE_CLASS_LEFT
const STYLE_CLASS_LEVEL_BAR = C.GTK_STYLE_CLASS_LEVEL_BAR
const STYLE_CLASS_LINKED = C.GTK_STYLE_CLASS_LINKED
const STYLE_CLASS_MARK = C.GTK_STYLE_CLASS_MARK
const STYLE_CLASS_MENU = C.GTK_STYLE_CLASS_MENU
const STYLE_CLASS_MENUBAR = C.GTK_STYLE_CLASS_MENUBAR
const STYLE_CLASS_MENUITEM = C.GTK_STYLE_CLASS_MENUITEM
const STYLE_CLASS_NOTEBOOK = C.GTK_STYLE_CLASS_NOTEBOOK
const STYLE_CLASS_OSD = C.GTK_STYLE_CLASS_OSD
const STYLE_CLASS_PANE_SEPARATOR = C.GTK_STYLE_CLASS_PANE_SEPARATOR
const STYLE_CLASS_PRIMARY_TOOLBAR = C.GTK_STYLE_CLASS_PRIMARY_TOOLBAR
const STYLE_CLASS_PROGRESSBAR = C.GTK_STYLE_CLASS_PROGRESSBAR
const STYLE_CLASS_PULSE = C.GTK_STYLE_CLASS_PULSE
const STYLE_CLASS_QUESTION = C.GTK_STYLE_CLASS_QUESTION
const STYLE_CLASS_RADIO = C.GTK_STYLE_CLASS_RADIO
const STYLE_CLASS_RAISED = C.GTK_STYLE_CLASS_RAISED
const STYLE_CLASS_RIGHT = C.GTK_STYLE_CLASS_RIGHT
const STYLE_CLASS_RUBBERBAND = C.GTK_STYLE_CLASS_RUBBERBAND
const STYLE_CLASS_SCALE = C.GTK_STYLE_CLASS_SCALE
const STYLE_CLASS_SCALE_HAS_MARKS_ABOVE = C.GTK_STYLE_CLASS_SCALE_HAS_MARKS_ABOVE
const STYLE_CLASS_SCALE_HAS_MARKS_BELOW = C.GTK_STYLE_CLASS_SCALE_HAS_MARKS_BELOW
const STYLE_CLASS_SCROLLBAR = C.GTK_STYLE_CLASS_SCROLLBAR
const STYLE_CLASS_SCROLLBARS_JUNCTION = C.GTK_STYLE_CLASS_SCROLLBARS_JUNCTION
const STYLE_CLASS_SEPARATOR = C.GTK_STYLE_CLASS_SEPARATOR
const STYLE_CLASS_SIDEBAR = C.GTK_STYLE_CLASS_SIDEBAR
const STYLE_CLASS_SLIDER = C.GTK_STYLE_CLASS_SLIDER
const STYLE_CLASS_SPINBUTTON = C.GTK_STYLE_CLASS_SPINBUTTON
const STYLE_CLASS_SPINNER = C.GTK_STYLE_CLASS_SPINNER
const STYLE_CLASS_TOOLBAR = C.GTK_STYLE_CLASS_TOOLBAR
const STYLE_CLASS_TOOLTIP = C.GTK_STYLE_CLASS_TOOLTIP
const STYLE_CLASS_TOP = C.GTK_STYLE_CLASS_TOP
const STYLE_CLASS_TROUGH = C.GTK_STYLE_CLASS_TROUGH
const STYLE_CLASS_VERTICAL = C.GTK_STYLE_CLASS_VERTICAL
const STYLE_CLASS_VIEW = C.GTK_STYLE_CLASS_VIEW
const STYLE_CLASS_WARNING = C.GTK_STYLE_CLASS_WARNING
const STYLE_PROPERTY_BACKGROUND_COLOR = C.GTK_STYLE_PROPERTY_BACKGROUND_COLOR
const STYLE_PROPERTY_BACKGROUND_IMAGE = C.GTK_STYLE_PROPERTY_BACKGROUND_IMAGE
const STYLE_PROPERTY_BORDER_COLOR = C.GTK_STYLE_PROPERTY_BORDER_COLOR
const STYLE_PROPERTY_BORDER_RADIUS = C.GTK_STYLE_PROPERTY_BORDER_RADIUS
const STYLE_PROPERTY_BORDER_STYLE = C.GTK_STYLE_PROPERTY_BORDER_STYLE
const STYLE_PROPERTY_BORDER_WIDTH = C.GTK_STYLE_PROPERTY_BORDER_WIDTH
const STYLE_PROPERTY_COLOR = C.GTK_STYLE_PROPERTY_COLOR
const STYLE_PROPERTY_FONT = C.GTK_STYLE_PROPERTY_FONT
const STYLE_PROPERTY_MARGIN = C.GTK_STYLE_PROPERTY_MARGIN
const STYLE_PROPERTY_PADDING = C.GTK_STYLE_PROPERTY_PADDING
const STYLE_PROVIDER_PRIORITY_APPLICATION = C.GTK_STYLE_PROVIDER_PRIORITY_APPLICATION
const STYLE_PROVIDER_PRIORITY_FALLBACK = C.GTK_STYLE_PROVIDER_PRIORITY_FALLBACK
const STYLE_PROVIDER_PRIORITY_SETTINGS = C.GTK_STYLE_PROVIDER_PRIORITY_SETTINGS
const STYLE_PROVIDER_PRIORITY_THEME = C.GTK_STYLE_PROVIDER_PRIORITY_THEME
const STYLE_PROVIDER_PRIORITY_USER = C.GTK_STYLE_PROVIDER_PRIORITY_USER
const STYLE_REGION_COLUMN = C.GTK_STYLE_REGION_COLUMN
const STYLE_REGION_COLUMN_HEADER = C.GTK_STYLE_REGION_COLUMN_HEADER
const STYLE_REGION_ROW = C.GTK_STYLE_REGION_ROW
const STYLE_REGION_TAB = C.GTK_STYLE_REGION_TAB
const TEXT_VIEW_PRIORITY_VALIDATE = C.GTK_TEXT_VIEW_PRIORITY_VALIDATE
type ToolbarClass C.GtkToolbarClass
type ListStoreClass C.GtkListStoreClass
type InfoBarPrivate C.GtkInfoBarPrivate
type CellRendererSpinnerPrivate C.GtkCellRendererSpinnerPrivate
type CellRendererClass C.GtkCellRendererClass
type RadioMenuItemClass C.GtkRadioMenuItemClass
type OverlayClass C.GtkOverlayClass
type FixedClass C.GtkFixedClass
type FramePrivate C.GtkFramePrivate
type SwitchClass C.GtkSwitchClass
type SelectionData C.GtkSelectionData
type MenuItemClass C.GtkMenuItemClass
type ToggleActionClass C.GtkToggleActionClass
type SettingsValue C.GtkSettingsValue
type CellLayoutIface C.GtkCellLayoutIface
type ToolItemGroupPrivate C.GtkToolItemGroupPrivate
type TextViewClass C.GtkTextViewClass
type FontChooserDialogPrivate C.GtkFontChooserDialogPrivate
type HSVPrivate C.GtkHSVPrivate
type TextAppearance C.GtkTextAppearance
type StatusbarPrivate C.GtkStatusbarPrivate
type InvisibleClass C.GtkInvisibleClass
type TearoffMenuItemPrivate C.GtkTearoffMenuItemPrivate
type FontSelectionDialogPrivate C.GtkFontSelectionDialogPrivate
type ComboBoxPrivate C.GtkComboBoxPrivate
type ColorButtonPrivate C.GtkColorButtonPrivate
type CellRendererSpinClass C.GtkCellRendererSpinClass
type RecentChooserWidgetPrivate C.GtkRecentChooserWidgetPrivate
type ComboBoxTextPrivate C.GtkComboBoxTextPrivate
type TreeStorePrivate C.GtkTreeStorePrivate
type ActionClass C.GtkActionClass
type RangePrivate C.GtkRangePrivate
type StatusbarClass C.GtkStatusbarClass
type ColorSelectionDialogClass C.GtkColorSelectionDialogClass
type FontSelectionClass C.GtkFontSelectionClass
type EditableInterface C.GtkEditableInterface
type TextMarkClass C.GtkTextMarkClass
type ToggleActionPrivate C.GtkToggleActionPrivate
type CellRendererClassPrivate C.GtkCellRendererClassPrivate
type FrameClass C.GtkFrameClass
type ToolItemPrivate C.GtkToolItemPrivate
type PanedClass C.GtkPanedClass
type TableChild C.GtkTableChild
type EntryClass C.GtkEntryClass
type ColorChooserDialogPrivate C.GtkColorChooserDialogPrivate
type RadioActionPrivate C.GtkRadioActionPrivate
type CssProviderPrivate C.GtkCssProviderPrivate
type EntryCompletionClass C.GtkEntryCompletionClass
type BoxClass C.GtkBoxClass
type TreeStoreClass C.GtkTreeStoreClass
type CellRendererAccelPrivate C.GtkCellRendererAccelPrivate
type AboutDialogPrivate C.GtkAboutDialogPrivate
type TreeModelSortPrivate C.GtkTreeModelSortPrivate
type ApplicationWindowPrivate C.GtkApplicationWindowPrivate
type VScaleClass C.GtkVScaleClass
type TreeModelIface C.GtkTreeModelIface
type TextTagTableClass C.GtkTextTagTableClass
type ToolButtonClass C.GtkToolButtonClass
type ToolItemGroupClass C.GtkToolItemGroupClass
type OverlayPrivate C.GtkOverlayPrivate
type HandleBoxPrivate C.GtkHandleBoxPrivate
type CellRendererAccelClass C.GtkCellRendererAccelClass
type ColorSelectionPrivate C.GtkColorSelectionPrivate
type HButtonBoxClass C.GtkHButtonBoxClass
type CellRendererPrivate C.GtkCellRendererPrivate
type AppChooserButtonPrivate C.GtkAppChooserButtonPrivate
type CellViewClass C.GtkCellViewClass
type NotebookPrivate C.GtkNotebookPrivate
type BindingEntry C.GtkBindingEntry
type ImagePrivate C.GtkImagePrivate
type IconFactoryClass C.GtkIconFactoryClass
type TargetList C.GtkTargetList
type ToggleButtonClass C.GtkToggleButtonClass
type RadioButtonPrivate C.GtkRadioButtonPrivate
type SeparatorClass C.GtkSeparatorClass
type NumerableIconClass C.GtkNumerableIconClass
type ExpanderClass C.GtkExpanderClass
type ScaleButtonClass C.GtkScaleButtonClass
type PrintOperationPreviewIface C.GtkPrintOperationPreviewIface
type SeparatorToolItemPrivate C.GtkSeparatorToolItemPrivate
type MessageDialogPrivate C.GtkMessageDialogPrivate
type ColorChooserInterface C.GtkColorChooserInterface
type EventBoxClass C.GtkEventBoxClass
type BinClass C.GtkBinClass
type SeparatorMenuItemClass C.GtkSeparatorMenuItemClass
type ActionEntry C.GtkActionEntry
type HScaleClass C.GtkHScaleClass
type ContainerClass C.GtkContainerClass
type FontChooserWidgetClass C.GtkFontChooserWidgetClass
type CheckMenuItemClass C.GtkCheckMenuItemClass
type EventBoxPrivate C.GtkEventBoxPrivate
type LevelBarClass C.GtkLevelBarClass
type ActionGroupPrivate C.GtkActionGroupPrivate
type IMContextSimplePrivate C.GtkIMContextSimplePrivate
type LockButtonClass C.GtkLockButtonClass
type UIManagerClass C.GtkUIManagerClass
type CellAreaBoxClass C.GtkCellAreaBoxClass
type ScaleClass C.GtkScaleClass
type StatusIconClass C.GtkStatusIconClass
type MountOperationPrivate C.GtkMountOperationPrivate
type CellRendererSpinPrivate C.GtkCellRendererSpinPrivate
type RecentChooserMenuPrivate C.GtkRecentChooserMenuPrivate
type WidgetClassPrivate C.GtkWidgetClassPrivate
type SpinnerClass C.GtkSpinnerClass
type CellRendererTogglePrivate C.GtkCellRendererTogglePrivate
type ToggleToolButtonPrivate C.GtkToggleToolButtonPrivate
type MessageDialogClass C.GtkMessageDialogClass
type VPanedClass C.GtkVPanedClass
type ScrolledWindowClass C.GtkScrolledWindowClass
type CellRendererTextPrivate C.GtkCellRendererTextPrivate
type FileChooserDialogPrivate C.GtkFileChooserDialogPrivate
type MenuShellPrivate C.GtkMenuShellPrivate
type IMContextInfo C.GtkIMContextInfo
type WindowGroupPrivate C.GtkWindowGroupPrivate
type CellViewPrivate C.GtkCellViewPrivate
type SpinButtonPrivate C.GtkSpinButtonPrivate
type IconViewPrivate C.GtkIconViewPrivate
type ScrollableInterface C.GtkScrollableInterface
type ColorChooserDialogClass C.GtkColorChooserDialogClass
type IMMulticontextPrivate C.GtkIMMulticontextPrivate
type VScrollbarClass C.GtkVScrollbarClass
type FileChooserWidgetClass C.GtkFileChooserWidgetClass
type FontSelectionPrivate C.GtkFontSelectionPrivate
type ColorChooserWidgetPrivate C.GtkColorChooserWidgetPrivate
type TablePrivate C.GtkTablePrivate
type VSeparatorClass C.GtkVSeparatorClass
type ActionableInterface C.GtkActionableInterface
type SettingsPrivate C.GtkSettingsPrivate
type VolumeButtonClass C.GtkVolumeButtonClass
type SizeGroupClass C.GtkSizeGroupClass
type TreeModelFilterPrivate C.GtkTreeModelFilterPrivate
type AccelKey C.GtkAccelKey
type LabelSelectionInfo C.GtkLabelSelectionInfo
type PrintOperationClass C.GtkPrintOperationClass
type TextTagPrivate C.GtkTextTagPrivate
type TreeSortableIface C.GtkTreeSortableIface
type LinkButtonPrivate C.GtkLinkButtonPrivate
type TextTagClass C.GtkTextTagClass
type AlignmentClass C.GtkAlignmentClass
type FontChooserWidgetPrivate C.GtkFontChooserWidgetPrivate
type TextChildAnchorClass C.GtkTextChildAnchorClass
type TreeViewClass C.GtkTreeViewClass
type RecentActionPrivate C.GtkRecentActionPrivate
type TreeSelectionPrivate C.GtkTreeSelectionPrivate
type CellRendererComboPrivate C.GtkCellRendererComboPrivate
type SocketClass C.GtkSocketClass
type ToggleToolButtonClass C.GtkToggleToolButtonClass
type AppChooserWidgetClass C.GtkAppChooserWidgetClass
type ToggleActionEntry C.GtkToggleActionEntry
type RecentActionClass C.GtkRecentActionClass
type IconViewClass C.GtkIconViewClass
type FontButtonClass C.GtkFontButtonClass
type CalendarPrivate C.GtkCalendarPrivate
type SeparatorToolItemClass C.GtkSeparatorToolItemClass
type HPanedClass C.GtkHPanedClass
type RadioButtonClass C.GtkRadioButtonClass
type CalendarClass C.GtkCalendarClass
type FontButtonPrivate C.GtkFontButtonPrivate
type AccessiblePrivate C.GtkAccessiblePrivate
type TreeSelectionClass C.GtkTreeSelectionClass
type BuilderPrivate C.GtkBuilderPrivate
type ToolItemClass C.GtkToolItemClass
type Requisition C.GtkRequisition
type CellRendererPixbufClass C.GtkCellRendererPixbufClass
type MenuShellClass C.GtkMenuShellClass
type MenuButtonPrivate C.GtkMenuButtonPrivate
type SizeGroupPrivate C.GtkSizeGroupPrivate
type SpinnerPrivate C.GtkSpinnerPrivate
type TreeDragDestIface C.GtkTreeDragDestIface
type AccelMapClass C.GtkAccelMapClass
type TreeRowReference C.GtkTreeRowReference
type TreeModelSortClass C.GtkTreeModelSortClass
type ViewportClass C.GtkViewportClass
type AboutDialogClass C.GtkAboutDialogClass
type EntryBufferClass C.GtkEntryBufferClass
type TextIter C.GtkTextIter
type MenuBarClass C.GtkMenuBarClass
type ViewportPrivate C.GtkViewportPrivate
type AppChooserDialogPrivate C.GtkAppChooserDialogPrivate
type LabelClass C.GtkLabelClass
type EntryCompletionPrivate C.GtkEntryCompletionPrivate
type SwitchPrivate C.GtkSwitchPrivate
type SeparatorPrivate C.GtkSeparatorPrivate
type AccelGroupPrivate C.GtkAccelGroupPrivate
type CssSection C.GtkCssSection
type MenuItemPrivate C.GtkMenuItemPrivate
type ColorSelectionClass C.GtkColorSelectionClass
type TextTagTablePrivate C.GtkTextTagTablePrivate
type FileChooserDialogClass C.GtkFileChooserDialogClass
type LinkButtonClass C.GtkLinkButtonClass
type ThemeEngine C.GtkThemeEngine
type ListStorePrivate C.GtkListStorePrivate
type AccessibleClass C.GtkAccessibleClass
type CellRendererProgressClass C.GtkCellRendererProgressClass
type AccelGroupEntry C.GtkAccelGroupEntry
type ContainerPrivate C.GtkContainerPrivate
type ToolButtonPrivate C.GtkToolButtonPrivate
type ColorButtonClass C.GtkColorButtonClass
type ButtonPrivate C.GtkButtonPrivate
type TextBufferPrivate C.GtkTextBufferPrivate
type ActionPrivate C.GtkActionPrivate
type StatusIconPrivate C.GtkStatusIconPrivate
type MiscPrivate C.GtkMiscPrivate
type LabelPrivate C.GtkLabelPrivate
type ProgressBarPrivate C.GtkProgressBarPrivate
type IconSet C.GtkIconSet
type ToolbarPrivate C.GtkToolbarPrivate
type TreeModelFilterClass C.GtkTreeModelFilterClass
type RangeClass C.GtkRangeClass
type RcStyleClass C.GtkRcStyleClass
type AppChooserWidgetPrivate C.GtkAppChooserWidgetPrivate
type RecentData C.GtkRecentData
type CellAreaBoxPrivate C.GtkCellAreaBoxPrivate
type TableRowCol C.GtkTableRowCol
type TreeViewColumnClass C.GtkTreeViewColumnClass
type FileChooserButtonPrivate C.GtkFileChooserButtonPrivate
type HSVClass C.GtkHSVClass
type ToolShellIface C.GtkToolShellIface
type StylePropertiesPrivate C.GtkStylePropertiesPrivate
type RcContext C.GtkRcContext
type CheckMenuItemPrivate C.GtkCheckMenuItemPrivate
type FixedPrivate C.GtkFixedPrivate
type IMMulticontextClass C.GtkIMMulticontextClass
type TextBufferClass C.GtkTextBufferClass
type FixedChild C.GtkFixedChild
type AccelLabelClass C.GtkAccelLabelClass
type TreeViewColumnPrivate C.GtkTreeViewColumnPrivate
type ImageMenuItemClass C.GtkImageMenuItemClass
type HSeparatorClass C.GtkHSeparatorClass
type AdjustmentClass C.GtkAdjustmentClass
type WindowClass C.GtkWindowClass
type VBoxClass C.GtkVBoxClass
type VButtonBoxClass C.GtkVButtonBoxClass
type BindingSet C.GtkBindingSet
type BuildableIface C.GtkBuildableIface
type RadioActionClass C.GtkRadioActionClass
type RecentManagerClass C.GtkRecentManagerClass
type ColorChooserWidgetClass C.GtkColorChooserWidgetClass
type WidgetPrivate C.GtkWidgetPrivate
type UIManagerPrivate C.GtkUIManagerPrivate
type ApplicationClass C.GtkApplicationClass
type RecentManagerPrivate C.GtkRecentManagerPrivate
type CheckButtonClass C.GtkCheckButtonClass
type ComboBoxClass C.GtkComboBoxClass
type MenuBarPrivate C.GtkMenuBarPrivate
type MenuToolButtonPrivate C.GtkMenuToolButtonPrivate
type AspectFrameClass C.GtkAspectFrameClass
type FontChooserDialogClass C.GtkFontChooserDialogClass
type CellRendererPixbufPrivate C.GtkCellRendererPixbufPrivate
type OffscreenWindowClass C.GtkOffscreenWindowClass
type WidgetPath C.GtkWidgetPath
type ThemingEngineClass C.GtkThemingEngineClass
type StyleContextClass C.GtkStyleContextClass
type RecentChooserIface C.GtkRecentChooserIface
type ScaleButtonPrivate C.GtkScaleButtonPrivate
type FileFilterInfo C.GtkFileFilterInfo
type IconFactoryPrivate C.GtkIconFactoryPrivate
type PageRange C.GtkPageRange
type StyleContextPrivate C.GtkStyleContextPrivate
type IMContextClass C.GtkIMContextClass
type RadioMenuItemPrivate C.GtkRadioMenuItemPrivate
type LockButtonPrivate C.GtkLockButtonPrivate
type BuilderClass C.GtkBuilderClass
type MountOperationClass C.GtkMountOperationClass
type CellAreaContextClass C.GtkCellAreaContextClass
type DialogPrivate C.GtkDialogPrivate
type PaperSize C.GtkPaperSize
type LevelBarPrivate C.GtkLevelBarPrivate
type SpinButtonClass C.GtkSpinButtonClass
type TearoffMenuItemClass C.GtkTearoffMenuItemClass
type PlugClass C.GtkPlugClass
type RadioToolButtonClass C.GtkRadioToolButtonClass
type CellAreaPrivate C.GtkCellAreaPrivate
type TreeViewPrivate C.GtkTreeViewPrivate
type ToggleButtonPrivate C.GtkToggleButtonPrivate
type RecentFilterInfo C.GtkRecentFilterInfo
type IconInfo C.GtkIconInfo
type ProgressBarClass C.GtkProgressBarClass
type FontSelectionDialogClass C.GtkFontSelectionDialogClass
type CellEditableIface C.GtkCellEditableIface
type SettingsClass C.GtkSettingsClass
type AdjustmentPrivate C.GtkAdjustmentPrivate
type TreePath C.GtkTreePath
type ActivatableIface C.GtkActivatableIface
type Border C.GtkBorder
type LayoutClass C.GtkLayoutClass
type HBoxClass C.GtkHBoxClass
type LayoutPrivate C.GtkLayoutPrivate
type MiscClass C.GtkMiscClass
type AccelLabelPrivate C.GtkAccelLabelPrivate
type TreeIter C.GtkTreeIter
type ToolPaletteClass C.GtkToolPaletteClass
type Gradient C.GtkGradient
type CellRendererComboClass C.GtkCellRendererComboClass
type FontChooserIface C.GtkFontChooserIface
type CellRendererTextClass C.GtkCellRendererTextClass
type IconSource C.GtkIconSource
type WindowPrivate C.GtkWindowPrivate
type CssProviderClass C.GtkCssProviderClass
type GridPrivate C.GtkGridPrivate
type FileChooserButtonClass C.GtkFileChooserButtonClass
type StylePropertiesClass C.GtkStylePropertiesClass
type HScrollbarClass C.GtkHScrollbarClass
type RecentInfo C.GtkRecentInfo
type ButtonClass C.GtkButtonClass
type CellAreaContextPrivate C.GtkCellAreaContextPrivate
type OrientableIface C.GtkOrientableIface
type SearchEntryClass C.GtkSearchEntryClass
type ThemingEnginePrivate C.GtkThemingEnginePrivate
type ImageClass C.GtkImageClass
type CellRendererSpinnerClass C.GtkCellRendererSpinnerClass
type StyleClass C.GtkStyleClass
type ArrowClass C.GtkArrowClass
type IconThemeClass C.GtkIconThemeClass
type CellAreaClass C.GtkCellAreaClass
type MenuPrivate C.GtkMenuPrivate
type AssistantPrivate C.GtkAssistantPrivate
type ExpanderPrivate C.GtkExpanderPrivate
type ColorSelectionDialogPrivate C.GtkColorSelectionDialogPrivate
type ScalePrivate C.GtkScalePrivate
type ImageMenuItemPrivate C.GtkImageMenuItemPrivate
type WidgetClass C.GtkWidgetClass
type InvisiblePrivate C.GtkInvisiblePrivate
type TextViewPrivate C.GtkTextViewPrivate
type RecentChooserDialogClass C.GtkRecentChooserDialogClass
type AppChooserDialogClass C.GtkAppChooserDialogClass
type PrintOperationPrivate C.GtkPrintOperationPrivate
type IMContextSimpleClass C.GtkIMContextSimpleClass
type SymbolicColor C.GtkSymbolicColor
type ComboBoxTextClass C.GtkComboBoxTextClass
type SocketPrivate C.GtkSocketPrivate
type MenuClass C.GtkMenuClass
type ArrowPrivate C.GtkArrowPrivate
type PanedPrivate C.GtkPanedPrivate
type BinPrivate C.GtkBinPrivate
type AccelGroupClass C.GtkAccelGroupClass
type TextBTree C.GtkTextBTree
type WindowGroupClass C.GtkWindowGroupClass
type RadioActionEntry C.GtkRadioActionEntry
type RecentChooserWidgetClass C.GtkRecentChooserWidgetClass
type GridClass C.GtkGridClass
type PlugPrivate C.GtkPlugPrivate
type AlignmentPrivate C.GtkAlignmentPrivate
type MenuToolButtonClass C.GtkMenuToolButtonClass
type CellRendererProgressPrivate C.GtkCellRendererProgressPrivate
type BindingSignal C.GtkBindingSignal
type WidgetAuxInfo C.GtkWidgetAuxInfo
type TargetEntry C.GtkTargetEntry
type ButtonBoxClass C.GtkButtonBoxClass
type TableClass C.GtkTableClass
type ScrollbarClass C.GtkScrollbarClass
type EntryPrivate C.GtkEntryPrivate
type BindingArg C.GtkBindingArg
type ButtonBoxPrivate C.GtkButtonBoxPrivate
type RecentChooserDialogPrivate C.GtkRecentChooserDialogPrivate
type WindowGeometryInfo C.GtkWindowGeometryInfo
type InfoBarClass C.GtkInfoBarClass
type FileChooserWidgetPrivate C.GtkFileChooserWidgetPrivate
type AssistantClass C.GtkAssistantClass
type ApplicationWindowClass C.GtkApplicationWindowClass
type RecentChooserMenuClass C.GtkRecentChooserMenuClass
type NotebookClass C.GtkNotebookClass
type BoxPrivate C.GtkBoxPrivate
type TreeDragSourceIface C.GtkTreeDragSourceIface
type HandleBoxClass C.GtkHandleBoxClass
type CellRendererToggleClass C.GtkCellRendererToggleClass
type AppChooserButtonClass C.GtkAppChooserButtonClass
type StockItem C.GtkStockItem
type MenuButtonClass C.GtkMenuButtonClass
type TextAttributes C.GtkTextAttributes
type ApplicationPrivate C.GtkApplicationPrivate
type DrawingAreaClass C.GtkDrawingAreaClass
type EntryBufferPrivate C.GtkEntryBufferPrivate
type DialogClass C.GtkDialogClass
type RequestedSize C.GtkRequestedSize
type AspectFramePrivate C.GtkAspectFramePrivate
type ActionGroupClass C.GtkActionGroupClass
type IconThemePrivate C.GtkIconThemePrivate
type ToolPalettePrivate C.GtkToolPalettePrivate
type ScrolledWindowPrivate C.GtkScrolledWindowPrivate
type StyleProviderIface C.GtkStyleProviderIface
type NumerableIconPrivate C.GtkNumerableIconPrivate
